//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18213
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18213.
// 
#pragma warning disable 1591

namespace SDA.wsInsercionDatosBen {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsInsertaDatosBeneficiosSoap", Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx")]
    public partial class wsInsertaDatosBeneficios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertSocioBeneficioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertAnalisisOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertBeneficiarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertCaptacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertColocacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertSiniestrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertEmisionPrimasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstatusReclamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPLusCaptacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarBeneficiarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCaptacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarColocacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsInsertaDatosBeneficios() {
            this.Url = global::SDA.Properties.Settings.Default.SDA_wsInsercionDatosBen_wsInsertaDatosBeneficios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertSocioBeneficioCompletedEventHandler InsertSocioBeneficioCompleted;
        
        /// <remarks/>
        public event InsertDocumentoCompletedEventHandler InsertDocumentoCompleted;
        
        /// <remarks/>
        public event InsertAnalisisCompletedEventHandler InsertAnalisisCompleted;
        
        /// <remarks/>
        public event InsertBeneficiarioCompletedEventHandler InsertBeneficiarioCompleted;
        
        /// <remarks/>
        public event InsertCaptacionCompletedEventHandler InsertCaptacionCompleted;
        
        /// <remarks/>
        public event InsertColocacionCompletedEventHandler InsertColocacionCompleted;
        
        /// <remarks/>
        public event InsertSiniestrosCompletedEventHandler InsertSiniestrosCompleted;
        
        /// <remarks/>
        public event InsertEmisionPrimasCompletedEventHandler InsertEmisionPrimasCompleted;
        
        /// <remarks/>
        public event EstatusReclamoCompletedEventHandler EstatusReclamoCompleted;
        
        /// <remarks/>
        public event InsertPLusCaptacionCompletedEventHandler InsertPLusCaptacionCompleted;
        
        /// <remarks/>
        public event EliminarDocumentoCompletedEventHandler EliminarDocumentoCompleted;
        
        /// <remarks/>
        public event EliminarBeneficiarioCompletedEventHandler EliminarBeneficiarioCompleted;
        
        /// <remarks/>
        public event EliminarCaptacionCompletedEventHandler EliminarCaptacionCompleted;
        
        /// <remarks/>
        public event EliminarColocacionCompletedEventHandler EliminarColocacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtSocioBeneficio", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertSocioBeneficio(
                    string No_Socio, 
                    string Nombre, 
                    string Nombre_2, 
                    string Apellido_Pat, 
                    string Apellido_Mat, 
                    string Fecha_Nac, 
                    string Fecha_Ing, 
                    int Sexo, 
                    string Correo, 
                    string RFC, 
                    string Curp, 
                    int Ocupacion, 
                    int Edo_Civil, 
                    int Id_Sucursal, 
                    string Ano_Reclamo, 
                    string Fecha_Reclamo, 
                    int Id_Colonia, 
                    string Calle, 
                    string No_Ext, 
                    string No_Int, 
                    int Actual, 
                    int Id_Tipo_Dom, 
                    int Paqueteria, 
                    string No_Guia) {
            object[] results = this.Invoke("InsertSocioBeneficio", new object[] {
                        No_Socio,
                        Nombre,
                        Nombre_2,
                        Apellido_Pat,
                        Apellido_Mat,
                        Fecha_Nac,
                        Fecha_Ing,
                        Sexo,
                        Correo,
                        RFC,
                        Curp,
                        Ocupacion,
                        Edo_Civil,
                        Id_Sucursal,
                        Ano_Reclamo,
                        Fecha_Reclamo,
                        Id_Colonia,
                        Calle,
                        No_Ext,
                        No_Int,
                        Actual,
                        Id_Tipo_Dom,
                        Paqueteria,
                        No_Guia});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSocioBeneficioAsync(
                    string No_Socio, 
                    string Nombre, 
                    string Nombre_2, 
                    string Apellido_Pat, 
                    string Apellido_Mat, 
                    string Fecha_Nac, 
                    string Fecha_Ing, 
                    int Sexo, 
                    string Correo, 
                    string RFC, 
                    string Curp, 
                    int Ocupacion, 
                    int Edo_Civil, 
                    int Id_Sucursal, 
                    string Ano_Reclamo, 
                    string Fecha_Reclamo, 
                    int Id_Colonia, 
                    string Calle, 
                    string No_Ext, 
                    string No_Int, 
                    int Actual, 
                    int Id_Tipo_Dom, 
                    int Paqueteria, 
                    string No_Guia) {
            this.InsertSocioBeneficioAsync(No_Socio, Nombre, Nombre_2, Apellido_Pat, Apellido_Mat, Fecha_Nac, Fecha_Ing, Sexo, Correo, RFC, Curp, Ocupacion, Edo_Civil, Id_Sucursal, Ano_Reclamo, Fecha_Reclamo, Id_Colonia, Calle, No_Ext, No_Int, Actual, Id_Tipo_Dom, Paqueteria, No_Guia, null);
        }
        
        /// <remarks/>
        public void InsertSocioBeneficioAsync(
                    string No_Socio, 
                    string Nombre, 
                    string Nombre_2, 
                    string Apellido_Pat, 
                    string Apellido_Mat, 
                    string Fecha_Nac, 
                    string Fecha_Ing, 
                    int Sexo, 
                    string Correo, 
                    string RFC, 
                    string Curp, 
                    int Ocupacion, 
                    int Edo_Civil, 
                    int Id_Sucursal, 
                    string Ano_Reclamo, 
                    string Fecha_Reclamo, 
                    int Id_Colonia, 
                    string Calle, 
                    string No_Ext, 
                    string No_Int, 
                    int Actual, 
                    int Id_Tipo_Dom, 
                    int Paqueteria, 
                    string No_Guia, 
                    object userState) {
            if ((this.InsertSocioBeneficioOperationCompleted == null)) {
                this.InsertSocioBeneficioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSocioBeneficioOperationCompleted);
            }
            this.InvokeAsync("InsertSocioBeneficio", new object[] {
                        No_Socio,
                        Nombre,
                        Nombre_2,
                        Apellido_Pat,
                        Apellido_Mat,
                        Fecha_Nac,
                        Fecha_Ing,
                        Sexo,
                        Correo,
                        RFC,
                        Curp,
                        Ocupacion,
                        Edo_Civil,
                        Id_Sucursal,
                        Ano_Reclamo,
                        Fecha_Reclamo,
                        Id_Colonia,
                        Calle,
                        No_Ext,
                        No_Int,
                        Actual,
                        Id_Tipo_Dom,
                        Paqueteria,
                        No_Guia}, this.InsertSocioBeneficioOperationCompleted, userState);
        }
        
        private void OnInsertSocioBeneficioOperationCompleted(object arg) {
            if ((this.InsertSocioBeneficioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSocioBeneficioCompleted(this, new InsertSocioBeneficioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtDocumento", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertDocumento(int Id_Tipo_Doc, int Id_Sucursal, string No_Socio, int Verificar) {
            object[] results = this.Invoke("InsertDocumento", new object[] {
                        Id_Tipo_Doc,
                        Id_Sucursal,
                        No_Socio,
                        Verificar});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDocumentoAsync(int Id_Tipo_Doc, int Id_Sucursal, string No_Socio, int Verificar) {
            this.InsertDocumentoAsync(Id_Tipo_Doc, Id_Sucursal, No_Socio, Verificar, null);
        }
        
        /// <remarks/>
        public void InsertDocumentoAsync(int Id_Tipo_Doc, int Id_Sucursal, string No_Socio, int Verificar, object userState) {
            if ((this.InsertDocumentoOperationCompleted == null)) {
                this.InsertDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDocumentoOperationCompleted);
            }
            this.InvokeAsync("InsertDocumento", new object[] {
                        Id_Tipo_Doc,
                        Id_Sucursal,
                        No_Socio,
                        Verificar}, this.InsertDocumentoOperationCompleted, userState);
        }
        
        private void OnInsertDocumentoOperationCompleted(object arg) {
            if ((this.InsertDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDocumentoCompleted(this, new InsertDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtAnalisis", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertAnalisis(int Id_Reclamo, string Fecha_Actual, string Ultima_Fecha_Lab, string Fecha_Muerte, int Id_Causante, string Causa_Muerte, int Id_Fallecimiento, int Menor_Ahorrador) {
            object[] results = this.Invoke("InsertAnalisis", new object[] {
                        Id_Reclamo,
                        Fecha_Actual,
                        Ultima_Fecha_Lab,
                        Fecha_Muerte,
                        Id_Causante,
                        Causa_Muerte,
                        Id_Fallecimiento,
                        Menor_Ahorrador});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertAnalisisAsync(int Id_Reclamo, string Fecha_Actual, string Ultima_Fecha_Lab, string Fecha_Muerte, int Id_Causante, string Causa_Muerte, int Id_Fallecimiento, int Menor_Ahorrador) {
            this.InsertAnalisisAsync(Id_Reclamo, Fecha_Actual, Ultima_Fecha_Lab, Fecha_Muerte, Id_Causante, Causa_Muerte, Id_Fallecimiento, Menor_Ahorrador, null);
        }
        
        /// <remarks/>
        public void InsertAnalisisAsync(int Id_Reclamo, string Fecha_Actual, string Ultima_Fecha_Lab, string Fecha_Muerte, int Id_Causante, string Causa_Muerte, int Id_Fallecimiento, int Menor_Ahorrador, object userState) {
            if ((this.InsertAnalisisOperationCompleted == null)) {
                this.InsertAnalisisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertAnalisisOperationCompleted);
            }
            this.InvokeAsync("InsertAnalisis", new object[] {
                        Id_Reclamo,
                        Fecha_Actual,
                        Ultima_Fecha_Lab,
                        Fecha_Muerte,
                        Id_Causante,
                        Causa_Muerte,
                        Id_Fallecimiento,
                        Menor_Ahorrador}, this.InsertAnalisisOperationCompleted, userState);
        }
        
        private void OnInsertAnalisisOperationCompleted(object arg) {
            if ((this.InsertAnalisisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertAnalisisCompleted(this, new InsertAnalisisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtBeneficiario", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertBeneficiario(string Nombre_1, string Nombre_2, string Apellido_Pat, string Apellido_Mat, string Porcentaje, int Id_Reclamo, int Id_Beneficiario, int Op) {
            object[] results = this.Invoke("InsertBeneficiario", new object[] {
                        Nombre_1,
                        Nombre_2,
                        Apellido_Pat,
                        Apellido_Mat,
                        Porcentaje,
                        Id_Reclamo,
                        Id_Beneficiario,
                        Op});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertBeneficiarioAsync(string Nombre_1, string Nombre_2, string Apellido_Pat, string Apellido_Mat, string Porcentaje, int Id_Reclamo, int Id_Beneficiario, int Op) {
            this.InsertBeneficiarioAsync(Nombre_1, Nombre_2, Apellido_Pat, Apellido_Mat, Porcentaje, Id_Reclamo, Id_Beneficiario, Op, null);
        }
        
        /// <remarks/>
        public void InsertBeneficiarioAsync(string Nombre_1, string Nombre_2, string Apellido_Pat, string Apellido_Mat, string Porcentaje, int Id_Reclamo, int Id_Beneficiario, int Op, object userState) {
            if ((this.InsertBeneficiarioOperationCompleted == null)) {
                this.InsertBeneficiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertBeneficiarioOperationCompleted);
            }
            this.InvokeAsync("InsertBeneficiario", new object[] {
                        Nombre_1,
                        Nombre_2,
                        Apellido_Pat,
                        Apellido_Mat,
                        Porcentaje,
                        Id_Reclamo,
                        Id_Beneficiario,
                        Op}, this.InsertBeneficiarioOperationCompleted, userState);
        }
        
        private void OnInsertBeneficiarioOperationCompleted(object arg) {
            if ((this.InsertBeneficiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertBeneficiarioCompleted(this, new InsertBeneficiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtCaptacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertCaptacion(string Saldo, string Ultimo_mov, int Id_Cuenta, string Saldo_AditamentoJ, string Saldo_DobleI, int Id_Reclamo, int Id_Producto, int Id_Captacion, int Aditamento_Juv, int Doble_Indem, string Saldo_Total) {
            object[] results = this.Invoke("InsertCaptacion", new object[] {
                        Saldo,
                        Ultimo_mov,
                        Id_Cuenta,
                        Saldo_AditamentoJ,
                        Saldo_DobleI,
                        Id_Reclamo,
                        Id_Producto,
                        Id_Captacion,
                        Aditamento_Juv,
                        Doble_Indem,
                        Saldo_Total});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertCaptacionAsync(string Saldo, string Ultimo_mov, int Id_Cuenta, string Saldo_AditamentoJ, string Saldo_DobleI, int Id_Reclamo, int Id_Producto, int Id_Captacion, int Aditamento_Juv, int Doble_Indem, string Saldo_Total) {
            this.InsertCaptacionAsync(Saldo, Ultimo_mov, Id_Cuenta, Saldo_AditamentoJ, Saldo_DobleI, Id_Reclamo, Id_Producto, Id_Captacion, Aditamento_Juv, Doble_Indem, Saldo_Total, null);
        }
        
        /// <remarks/>
        public void InsertCaptacionAsync(string Saldo, string Ultimo_mov, int Id_Cuenta, string Saldo_AditamentoJ, string Saldo_DobleI, int Id_Reclamo, int Id_Producto, int Id_Captacion, int Aditamento_Juv, int Doble_Indem, string Saldo_Total, object userState) {
            if ((this.InsertCaptacionOperationCompleted == null)) {
                this.InsertCaptacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCaptacionOperationCompleted);
            }
            this.InvokeAsync("InsertCaptacion", new object[] {
                        Saldo,
                        Ultimo_mov,
                        Id_Cuenta,
                        Saldo_AditamentoJ,
                        Saldo_DobleI,
                        Id_Reclamo,
                        Id_Producto,
                        Id_Captacion,
                        Aditamento_Juv,
                        Doble_Indem,
                        Saldo_Total}, this.InsertCaptacionOperationCompleted, userState);
        }
        
        private void OnInsertCaptacionOperationCompleted(object arg) {
            if ((this.InsertCaptacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCaptacionCompleted(this, new InsertCaptacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtColocacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertColocacion(string Fecha_Prest, string Tasa_int, int Plazo, string Ult_Mov, string Saldo, int Tipo_Prest, int Id_Tipo_Cta, int Id_Reclamo, string Monto, int Id_Colocacion, int Id_Producto, string Saldo_Total, string Intereses_cubrir) {
            object[] results = this.Invoke("InsertColocacion", new object[] {
                        Fecha_Prest,
                        Tasa_int,
                        Plazo,
                        Ult_Mov,
                        Saldo,
                        Tipo_Prest,
                        Id_Tipo_Cta,
                        Id_Reclamo,
                        Monto,
                        Id_Colocacion,
                        Id_Producto,
                        Saldo_Total,
                        Intereses_cubrir});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertColocacionAsync(string Fecha_Prest, string Tasa_int, int Plazo, string Ult_Mov, string Saldo, int Tipo_Prest, int Id_Tipo_Cta, int Id_Reclamo, string Monto, int Id_Colocacion, int Id_Producto, string Saldo_Total, string Intereses_cubrir) {
            this.InsertColocacionAsync(Fecha_Prest, Tasa_int, Plazo, Ult_Mov, Saldo, Tipo_Prest, Id_Tipo_Cta, Id_Reclamo, Monto, Id_Colocacion, Id_Producto, Saldo_Total, Intereses_cubrir, null);
        }
        
        /// <remarks/>
        public void InsertColocacionAsync(string Fecha_Prest, string Tasa_int, int Plazo, string Ult_Mov, string Saldo, int Tipo_Prest, int Id_Tipo_Cta, int Id_Reclamo, string Monto, int Id_Colocacion, int Id_Producto, string Saldo_Total, string Intereses_cubrir, object userState) {
            if ((this.InsertColocacionOperationCompleted == null)) {
                this.InsertColocacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertColocacionOperationCompleted);
            }
            this.InvokeAsync("InsertColocacion", new object[] {
                        Fecha_Prest,
                        Tasa_int,
                        Plazo,
                        Ult_Mov,
                        Saldo,
                        Tipo_Prest,
                        Id_Tipo_Cta,
                        Id_Reclamo,
                        Monto,
                        Id_Colocacion,
                        Id_Producto,
                        Saldo_Total,
                        Intereses_cubrir}, this.InsertColocacionOperationCompleted, userState);
        }
        
        private void OnInsertColocacionOperationCompleted(object arg) {
            if ((this.InsertColocacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertColocacionCompleted(this, new InsertColocacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtSiniestros", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertSiniestros(string Cooperativa, int No_Reclamos, string Prestamo, string Ahorro, string Funerario, string Mutual, string PRO_DOS, string Monto_Mes, string No_Reclamos_Acum, string Monto_Acum) {
            object[] results = this.Invoke("InsertSiniestros", new object[] {
                        Cooperativa,
                        No_Reclamos,
                        Prestamo,
                        Ahorro,
                        Funerario,
                        Mutual,
                        PRO_DOS,
                        Monto_Mes,
                        No_Reclamos_Acum,
                        Monto_Acum});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSiniestrosAsync(string Cooperativa, int No_Reclamos, string Prestamo, string Ahorro, string Funerario, string Mutual, string PRO_DOS, string Monto_Mes, string No_Reclamos_Acum, string Monto_Acum) {
            this.InsertSiniestrosAsync(Cooperativa, No_Reclamos, Prestamo, Ahorro, Funerario, Mutual, PRO_DOS, Monto_Mes, No_Reclamos_Acum, Monto_Acum, null);
        }
        
        /// <remarks/>
        public void InsertSiniestrosAsync(string Cooperativa, int No_Reclamos, string Prestamo, string Ahorro, string Funerario, string Mutual, string PRO_DOS, string Monto_Mes, string No_Reclamos_Acum, string Monto_Acum, object userState) {
            if ((this.InsertSiniestrosOperationCompleted == null)) {
                this.InsertSiniestrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSiniestrosOperationCompleted);
            }
            this.InvokeAsync("InsertSiniestros", new object[] {
                        Cooperativa,
                        No_Reclamos,
                        Prestamo,
                        Ahorro,
                        Funerario,
                        Mutual,
                        PRO_DOS,
                        Monto_Mes,
                        No_Reclamos_Acum,
                        Monto_Acum}, this.InsertSiniestrosOperationCompleted, userState);
        }
        
        private void OnInsertSiniestrosOperationCompleted(object arg) {
            if ((this.InsertSiniestrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSiniestrosCompleted(this, new InsertSiniestrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtEmisionPrimas", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertEmisionPrimas(
                    string Plaza, 
                    string Prestamos_Miles, 
                    string Mayores_Miles, 
                    string Menores_Miles, 
                    string PP, 
                    string PA_Menor, 
                    string Basica, 
                    string Doble_Indem, 
                    string Aditamento_Juv, 
                    int Rango_Edad1, 
                    int Rango_Edad2, 
                    int Rango_Edad3, 
                    string Cobertura, 
                    string Apoyo_Fun1, 
                    string Apoyo_Fun2, 
                    string Apoyo_Fun3, 
                    string Apoyo_Fun_funcionarios, 
                    string Total_PA_PP_AF) {
            object[] results = this.Invoke("InsertEmisionPrimas", new object[] {
                        Plaza,
                        Prestamos_Miles,
                        Mayores_Miles,
                        Menores_Miles,
                        PP,
                        PA_Menor,
                        Basica,
                        Doble_Indem,
                        Aditamento_Juv,
                        Rango_Edad1,
                        Rango_Edad2,
                        Rango_Edad3,
                        Cobertura,
                        Apoyo_Fun1,
                        Apoyo_Fun2,
                        Apoyo_Fun3,
                        Apoyo_Fun_funcionarios,
                        Total_PA_PP_AF});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertEmisionPrimasAsync(
                    string Plaza, 
                    string Prestamos_Miles, 
                    string Mayores_Miles, 
                    string Menores_Miles, 
                    string PP, 
                    string PA_Menor, 
                    string Basica, 
                    string Doble_Indem, 
                    string Aditamento_Juv, 
                    int Rango_Edad1, 
                    int Rango_Edad2, 
                    int Rango_Edad3, 
                    string Cobertura, 
                    string Apoyo_Fun1, 
                    string Apoyo_Fun2, 
                    string Apoyo_Fun3, 
                    string Apoyo_Fun_funcionarios, 
                    string Total_PA_PP_AF) {
            this.InsertEmisionPrimasAsync(Plaza, Prestamos_Miles, Mayores_Miles, Menores_Miles, PP, PA_Menor, Basica, Doble_Indem, Aditamento_Juv, Rango_Edad1, Rango_Edad2, Rango_Edad3, Cobertura, Apoyo_Fun1, Apoyo_Fun2, Apoyo_Fun3, Apoyo_Fun_funcionarios, Total_PA_PP_AF, null);
        }
        
        /// <remarks/>
        public void InsertEmisionPrimasAsync(
                    string Plaza, 
                    string Prestamos_Miles, 
                    string Mayores_Miles, 
                    string Menores_Miles, 
                    string PP, 
                    string PA_Menor, 
                    string Basica, 
                    string Doble_Indem, 
                    string Aditamento_Juv, 
                    int Rango_Edad1, 
                    int Rango_Edad2, 
                    int Rango_Edad3, 
                    string Cobertura, 
                    string Apoyo_Fun1, 
                    string Apoyo_Fun2, 
                    string Apoyo_Fun3, 
                    string Apoyo_Fun_funcionarios, 
                    string Total_PA_PP_AF, 
                    object userState) {
            if ((this.InsertEmisionPrimasOperationCompleted == null)) {
                this.InsertEmisionPrimasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertEmisionPrimasOperationCompleted);
            }
            this.InvokeAsync("InsertEmisionPrimas", new object[] {
                        Plaza,
                        Prestamos_Miles,
                        Mayores_Miles,
                        Menores_Miles,
                        PP,
                        PA_Menor,
                        Basica,
                        Doble_Indem,
                        Aditamento_Juv,
                        Rango_Edad1,
                        Rango_Edad2,
                        Rango_Edad3,
                        Cobertura,
                        Apoyo_Fun1,
                        Apoyo_Fun2,
                        Apoyo_Fun3,
                        Apoyo_Fun_funcionarios,
                        Total_PA_PP_AF}, this.InsertEmisionPrimasOperationCompleted, userState);
        }
        
        private void OnInsertEmisionPrimasOperationCompleted(object arg) {
            if ((this.InsertEmisionPrimasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertEmisionPrimasCompleted(this, new InsertEmisionPrimasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Esta" +
            "tusReclamo", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EstatusReclamo(int Id_Edo_Beneficio, int Id_Reclamo) {
            object[] results = this.Invoke("EstatusReclamo", new object[] {
                        Id_Edo_Beneficio,
                        Id_Reclamo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EstatusReclamoAsync(int Id_Edo_Beneficio, int Id_Reclamo) {
            this.EstatusReclamoAsync(Id_Edo_Beneficio, Id_Reclamo, null);
        }
        
        /// <remarks/>
        public void EstatusReclamoAsync(int Id_Edo_Beneficio, int Id_Reclamo, object userState) {
            if ((this.EstatusReclamoOperationCompleted == null)) {
                this.EstatusReclamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstatusReclamoOperationCompleted);
            }
            this.InvokeAsync("EstatusReclamo", new object[] {
                        Id_Edo_Beneficio,
                        Id_Reclamo}, this.EstatusReclamoOperationCompleted, userState);
        }
        
        private void OnEstatusReclamoOperationCompleted(object arg) {
            if ((this.EstatusReclamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstatusReclamoCompleted(this, new EstatusReclamoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Inse" +
            "rtPLusCaptacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertPLusCaptacion(int Id_Reclamo, string Aditamento_Juv) {
            object[] results = this.Invoke("InsertPLusCaptacion", new object[] {
                        Id_Reclamo,
                        Aditamento_Juv});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPLusCaptacionAsync(int Id_Reclamo, string Aditamento_Juv) {
            this.InsertPLusCaptacionAsync(Id_Reclamo, Aditamento_Juv, null);
        }
        
        /// <remarks/>
        public void InsertPLusCaptacionAsync(int Id_Reclamo, string Aditamento_Juv, object userState) {
            if ((this.InsertPLusCaptacionOperationCompleted == null)) {
                this.InsertPLusCaptacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPLusCaptacionOperationCompleted);
            }
            this.InvokeAsync("InsertPLusCaptacion", new object[] {
                        Id_Reclamo,
                        Aditamento_Juv}, this.InsertPLusCaptacionOperationCompleted, userState);
        }
        
        private void OnInsertPLusCaptacionOperationCompleted(object arg) {
            if ((this.InsertPLusCaptacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPLusCaptacionCompleted(this, new InsertPLusCaptacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Elim" +
            "inarDocumento", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarDocumento(int Id_Documento, int Op) {
            object[] results = this.Invoke("EliminarDocumento", new object[] {
                        Id_Documento,
                        Op});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarDocumentoAsync(int Id_Documento, int Op) {
            this.EliminarDocumentoAsync(Id_Documento, Op, null);
        }
        
        /// <remarks/>
        public void EliminarDocumentoAsync(int Id_Documento, int Op, object userState) {
            if ((this.EliminarDocumentoOperationCompleted == null)) {
                this.EliminarDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDocumentoOperationCompleted);
            }
            this.InvokeAsync("EliminarDocumento", new object[] {
                        Id_Documento,
                        Op}, this.EliminarDocumentoOperationCompleted, userState);
        }
        
        private void OnEliminarDocumentoOperationCompleted(object arg) {
            if ((this.EliminarDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDocumentoCompleted(this, new EliminarDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Elim" +
            "inarBeneficiario", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarBeneficiario(int Id_Beneficiario, int Op) {
            object[] results = this.Invoke("EliminarBeneficiario", new object[] {
                        Id_Beneficiario,
                        Op});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarBeneficiarioAsync(int Id_Beneficiario, int Op) {
            this.EliminarBeneficiarioAsync(Id_Beneficiario, Op, null);
        }
        
        /// <remarks/>
        public void EliminarBeneficiarioAsync(int Id_Beneficiario, int Op, object userState) {
            if ((this.EliminarBeneficiarioOperationCompleted == null)) {
                this.EliminarBeneficiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarBeneficiarioOperationCompleted);
            }
            this.InvokeAsync("EliminarBeneficiario", new object[] {
                        Id_Beneficiario,
                        Op}, this.EliminarBeneficiarioOperationCompleted, userState);
        }
        
        private void OnEliminarBeneficiarioOperationCompleted(object arg) {
            if ((this.EliminarBeneficiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarBeneficiarioCompleted(this, new EliminarBeneficiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Elim" +
            "inarCaptacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarCaptacion(int Id_Captacion, int Op) {
            object[] results = this.Invoke("EliminarCaptacion", new object[] {
                        Id_Captacion,
                        Op});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarCaptacionAsync(int Id_Captacion, int Op) {
            this.EliminarCaptacionAsync(Id_Captacion, Op, null);
        }
        
        /// <remarks/>
        public void EliminarCaptacionAsync(int Id_Captacion, int Op, object userState) {
            if ((this.EliminarCaptacionOperationCompleted == null)) {
                this.EliminarCaptacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCaptacionOperationCompleted);
            }
            this.InvokeAsync("EliminarCaptacion", new object[] {
                        Id_Captacion,
                        Op}, this.EliminarCaptacionOperationCompleted, userState);
        }
        
        private void OnEliminarCaptacionOperationCompleted(object arg) {
            if ((this.EliminarCaptacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCaptacionCompleted(this, new EliminarCaptacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx/Elim" +
            "inarColocacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarColocacion(int Id_Colocacion, int Op) {
            object[] results = this.Invoke("EliminarColocacion", new object[] {
                        Id_Colocacion,
                        Op});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarColocacionAsync(int Id_Colocacion, int Op) {
            this.EliminarColocacionAsync(Id_Colocacion, Op, null);
        }
        
        /// <remarks/>
        public void EliminarColocacionAsync(int Id_Colocacion, int Op, object userState) {
            if ((this.EliminarColocacionOperationCompleted == null)) {
                this.EliminarColocacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarColocacionOperationCompleted);
            }
            this.InvokeAsync("EliminarColocacion", new object[] {
                        Id_Colocacion,
                        Op}, this.EliminarColocacionOperationCompleted, userState);
        }
        
        private void OnEliminarColocacionOperationCompleted(object arg) {
            if ((this.EliminarColocacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarColocacionCompleted(this, new EliminarColocacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsInsertaDatosBeneficios.asmx")]
    public partial class Error {
        
        private string mensajeField;
        
        private bool valorField;
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public bool Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertSocioBeneficioCompletedEventHandler(object sender, InsertSocioBeneficioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSocioBeneficioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSocioBeneficioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertDocumentoCompletedEventHandler(object sender, InsertDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertAnalisisCompletedEventHandler(object sender, InsertAnalisisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertAnalisisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertAnalisisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertBeneficiarioCompletedEventHandler(object sender, InsertBeneficiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertBeneficiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertBeneficiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertCaptacionCompletedEventHandler(object sender, InsertCaptacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCaptacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCaptacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertColocacionCompletedEventHandler(object sender, InsertColocacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertColocacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertColocacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertSiniestrosCompletedEventHandler(object sender, InsertSiniestrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSiniestrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSiniestrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertEmisionPrimasCompletedEventHandler(object sender, InsertEmisionPrimasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertEmisionPrimasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertEmisionPrimasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EstatusReclamoCompletedEventHandler(object sender, EstatusReclamoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstatusReclamoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstatusReclamoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InsertPLusCaptacionCompletedEventHandler(object sender, InsertPLusCaptacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPLusCaptacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPLusCaptacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EliminarDocumentoCompletedEventHandler(object sender, EliminarDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EliminarBeneficiarioCompletedEventHandler(object sender, EliminarBeneficiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarBeneficiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarBeneficiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EliminarCaptacionCompletedEventHandler(object sender, EliminarCaptacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCaptacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCaptacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EliminarColocacionCompletedEventHandler(object sender, EliminarColocacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarColocacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarColocacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591