//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.586.
// 
#pragma warning disable 1591

namespace SDA.correoPrybe {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsCorreoPrybeSoap", Namespace="http://seguros.prybe.coop/WSPrybe/wspf/wsPrybe.asmx")]
    public partial class wsCorreoPrybe : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviaCorreoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsCorreoPrybe() {
            this.Url = global::SDA.Properties.Settings.Default.SDA_correoPrybe_wsCorreoPrybe;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviaCorreoCompletedEventHandler EnviaCorreoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybe/wspf/wsPrybe.asmx/EnviaCorreo", RequestNamespace="http://seguros.prybe.coop/WSPrybe/wspf/wsPrybe.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybe/wspf/wsPrybe.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaCorreo(string toA, string fromA, string subject, string body, bool esHTML) {
            object[] results = this.Invoke("EnviaCorreo", new object[] {
                        toA,
                        fromA,
                        subject,
                        body,
                        esHTML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaCorreoAsync(string toA, string fromA, string subject, string body, bool esHTML) {
            this.EnviaCorreoAsync(toA, fromA, subject, body, esHTML, null);
        }
        
        /// <remarks/>
        public void EnviaCorreoAsync(string toA, string fromA, string subject, string body, bool esHTML, object userState) {
            if ((this.EnviaCorreoOperationCompleted == null)) {
                this.EnviaCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaCorreoOperationCompleted);
            }
            this.InvokeAsync("EnviaCorreo", new object[] {
                        toA,
                        fromA,
                        subject,
                        body,
                        esHTML}, this.EnviaCorreoOperationCompleted, userState);
        }
        
        private void OnEnviaCorreoOperationCompleted(object arg) {
            if ((this.EnviaCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaCorreoCompleted(this, new EnviaCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EnviaCorreoCompletedEventHandler(object sender, EnviaCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591