//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18213
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18213.
// 
#pragma warning disable 1591

namespace SDA.wsConsultaDatosBen {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsConsultaBeneficiosSoap", Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class wsConsultaBeneficios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CargaDatosSocioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaDatosSocioAltaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaDatosAnalisisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultasContabilidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaReportesBeneficiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultasSaldoTotalCaptacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultasSaldoTotalColocacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsConsultaBeneficios() {
            this.Url = global::SDA.Properties.Settings.Default.SDA_wsConsultaDatosBen_wsConsultaBeneficios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CargaDatosSocioCompletedEventHandler CargaDatosSocioCompleted;
        
        /// <remarks/>
        public event CargaDatosSocioAltaCompletedEventHandler CargaDatosSocioAltaCompleted;
        
        /// <remarks/>
        public event CargaDatosAnalisisCompletedEventHandler CargaDatosAnalisisCompleted;
        
        /// <remarks/>
        public event ConsultasContabilidadCompletedEventHandler ConsultasContabilidadCompleted;
        
        /// <remarks/>
        public event ConsultaReportesBeneficiosCompletedEventHandler ConsultaReportesBeneficiosCompleted;
        
        /// <remarks/>
        public event ConsultasSaldoTotalCaptacionCompletedEventHandler ConsultasSaldoTotalCaptacionCompleted;
        
        /// <remarks/>
        public event ConsultasSaldoTotalColocacionCompletedEventHandler ConsultasSaldoTotalColocacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/CargaDat" +
            "osSocio", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatosSocio CargaDatosSocio(string IdReclamo) {
            object[] results = this.Invoke("CargaDatosSocio", new object[] {
                        IdReclamo});
            return ((DatosSocio)(results[0]));
        }
        
        /// <remarks/>
        public void CargaDatosSocioAsync(string IdReclamo) {
            this.CargaDatosSocioAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void CargaDatosSocioAsync(string IdReclamo, object userState) {
            if ((this.CargaDatosSocioOperationCompleted == null)) {
                this.CargaDatosSocioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaDatosSocioOperationCompleted);
            }
            this.InvokeAsync("CargaDatosSocio", new object[] {
                        IdReclamo}, this.CargaDatosSocioOperationCompleted, userState);
        }
        
        private void OnCargaDatosSocioOperationCompleted(object arg) {
            if ((this.CargaDatosSocioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaDatosSocioCompleted(this, new CargaDatosSocioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/CargaDat" +
            "osSocioAlta", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatosSocioAlta CargaDatosSocioAlta(string NumSocio, string IdSucursal) {
            object[] results = this.Invoke("CargaDatosSocioAlta", new object[] {
                        NumSocio,
                        IdSucursal});
            return ((DatosSocioAlta)(results[0]));
        }
        
        /// <remarks/>
        public void CargaDatosSocioAltaAsync(string NumSocio, string IdSucursal) {
            this.CargaDatosSocioAltaAsync(NumSocio, IdSucursal, null);
        }
        
        /// <remarks/>
        public void CargaDatosSocioAltaAsync(string NumSocio, string IdSucursal, object userState) {
            if ((this.CargaDatosSocioAltaOperationCompleted == null)) {
                this.CargaDatosSocioAltaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaDatosSocioAltaOperationCompleted);
            }
            this.InvokeAsync("CargaDatosSocioAlta", new object[] {
                        NumSocio,
                        IdSucursal}, this.CargaDatosSocioAltaOperationCompleted, userState);
        }
        
        private void OnCargaDatosSocioAltaOperationCompleted(object arg) {
            if ((this.CargaDatosSocioAltaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaDatosSocioAltaCompleted(this, new CargaDatosSocioAltaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/CargaDat" +
            "osAnalisis", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatosAnalisis CargaDatosAnalisis(string IdReclamo) {
            object[] results = this.Invoke("CargaDatosAnalisis", new object[] {
                        IdReclamo});
            return ((DatosAnalisis)(results[0]));
        }
        
        /// <remarks/>
        public void CargaDatosAnalisisAsync(string IdReclamo) {
            this.CargaDatosAnalisisAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void CargaDatosAnalisisAsync(string IdReclamo, object userState) {
            if ((this.CargaDatosAnalisisOperationCompleted == null)) {
                this.CargaDatosAnalisisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaDatosAnalisisOperationCompleted);
            }
            this.InvokeAsync("CargaDatosAnalisis", new object[] {
                        IdReclamo}, this.CargaDatosAnalisisOperationCompleted, userState);
        }
        
        private void OnCargaDatosAnalisisOperationCompleted(object arg) {
            if ((this.CargaDatosAnalisisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaDatosAnalisisCompleted(this, new CargaDatosAnalisisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/Consulta" +
            "sContabilidad", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaContabilidad[] ConsultasContabilidad(string IdPlaza) {
            object[] results = this.Invoke("ConsultasContabilidad", new object[] {
                        IdPlaza});
            return ((ConsultaContabilidad[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultasContabilidadAsync(string IdPlaza) {
            this.ConsultasContabilidadAsync(IdPlaza, null);
        }
        
        /// <remarks/>
        public void ConsultasContabilidadAsync(string IdPlaza, object userState) {
            if ((this.ConsultasContabilidadOperationCompleted == null)) {
                this.ConsultasContabilidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultasContabilidadOperationCompleted);
            }
            this.InvokeAsync("ConsultasContabilidad", new object[] {
                        IdPlaza}, this.ConsultasContabilidadOperationCompleted, userState);
        }
        
        private void OnConsultasContabilidadOperationCompleted(object arg) {
            if ((this.ConsultasContabilidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultasContabilidadCompleted(this, new ConsultasContabilidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/Consulta" +
            "ReportesBeneficios", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaReportes[] ConsultaReportesBeneficios(string IdReclamo) {
            object[] results = this.Invoke("ConsultaReportesBeneficios", new object[] {
                        IdReclamo});
            return ((ConsultaReportes[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaReportesBeneficiosAsync(string IdReclamo) {
            this.ConsultaReportesBeneficiosAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultaReportesBeneficiosAsync(string IdReclamo, object userState) {
            if ((this.ConsultaReportesBeneficiosOperationCompleted == null)) {
                this.ConsultaReportesBeneficiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReportesBeneficiosOperationCompleted);
            }
            this.InvokeAsync("ConsultaReportesBeneficios", new object[] {
                        IdReclamo}, this.ConsultaReportesBeneficiosOperationCompleted, userState);
        }
        
        private void OnConsultaReportesBeneficiosOperationCompleted(object arg) {
            if ((this.ConsultaReportesBeneficiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReportesBeneficiosCompleted(this, new ConsultaReportesBeneficiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/Consulta" +
            "sSaldoTotalCaptacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaSaldoTotalCaptacion ConsultasSaldoTotalCaptacion(string IdReclamo) {
            object[] results = this.Invoke("ConsultasSaldoTotalCaptacion", new object[] {
                        IdReclamo});
            return ((ConsultaSaldoTotalCaptacion)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultasSaldoTotalCaptacionAsync(string IdReclamo) {
            this.ConsultasSaldoTotalCaptacionAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultasSaldoTotalCaptacionAsync(string IdReclamo, object userState) {
            if ((this.ConsultasSaldoTotalCaptacionOperationCompleted == null)) {
                this.ConsultasSaldoTotalCaptacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultasSaldoTotalCaptacionOperationCompleted);
            }
            this.InvokeAsync("ConsultasSaldoTotalCaptacion", new object[] {
                        IdReclamo}, this.ConsultasSaldoTotalCaptacionOperationCompleted, userState);
        }
        
        private void OnConsultasSaldoTotalCaptacionOperationCompleted(object arg) {
            if ((this.ConsultasSaldoTotalCaptacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultasSaldoTotalCaptacionCompleted(this, new ConsultasSaldoTotalCaptacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx/Consulta" +
            "sSaldoTotalColocacion", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaSaldoTotalColocacion ConsultasSaldoTotalColocacion(string IdReclamo) {
            object[] results = this.Invoke("ConsultasSaldoTotalColocacion", new object[] {
                        IdReclamo});
            return ((ConsultaSaldoTotalColocacion)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultasSaldoTotalColocacionAsync(string IdReclamo) {
            this.ConsultasSaldoTotalColocacionAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultasSaldoTotalColocacionAsync(string IdReclamo, object userState) {
            if ((this.ConsultasSaldoTotalColocacionOperationCompleted == null)) {
                this.ConsultasSaldoTotalColocacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultasSaldoTotalColocacionOperationCompleted);
            }
            this.InvokeAsync("ConsultasSaldoTotalColocacion", new object[] {
                        IdReclamo}, this.ConsultasSaldoTotalColocacionOperationCompleted, userState);
        }
        
        private void OnConsultasSaldoTotalColocacionOperationCompleted(object arg) {
            if ((this.ConsultasSaldoTotalColocacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultasSaldoTotalColocacionCompleted(this, new ConsultasSaldoTotalColocacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class DatosSocio {
        
        private string numReclamoField;
        
        private string nombreField;
        
        private string sucursalField;
        
        private string plazaField;
        
        private string numSocioField;
        
        private string fechaNacField;
        
        private string fechaIngField;
        
        private bool sexoField;
        
        private string ocupacionField;
        
        private string domicilioField;
        
        private string edadIngField;
        
        private string numeroPolizaField;
        
        private string cooperativaField;
        
        private string estadoBeneficioField;
        
        /// <comentarios/>
        public string NumReclamo {
            get {
                return this.numReclamoField;
            }
            set {
                this.numReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Plaza {
            get {
                return this.plazaField;
            }
            set {
                this.plazaField = value;
            }
        }
        
        /// <comentarios/>
        public string NumSocio {
            get {
                return this.numSocioField;
            }
            set {
                this.numSocioField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaIng {
            get {
                return this.fechaIngField;
            }
            set {
                this.fechaIngField = value;
            }
        }
        
        /// <comentarios/>
        public bool Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        public string Ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
        
        /// <comentarios/>
        public string EdadIng {
            get {
                return this.edadIngField;
            }
            set {
                this.edadIngField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroPoliza {
            get {
                return this.numeroPolizaField;
            }
            set {
                this.numeroPolizaField = value;
            }
        }
        
        /// <comentarios/>
        public string Cooperativa {
            get {
                return this.cooperativaField;
            }
            set {
                this.cooperativaField = value;
            }
        }
        
        /// <comentarios/>
        public string EstadoBeneficio {
            get {
                return this.estadoBeneficioField;
            }
            set {
                this.estadoBeneficioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class ConsultaSaldoTotalColocacion {
        
        private double saldoColocacionField;
        
        /// <comentarios/>
        public double SaldoColocacion {
            get {
                return this.saldoColocacionField;
            }
            set {
                this.saldoColocacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class ConsultaSaldoTotalCaptacion {
        
        private double saldoCaptacionField;
        
        /// <comentarios/>
        public double SaldoCaptacion {
            get {
                return this.saldoCaptacionField;
            }
            set {
                this.saldoCaptacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class ConsultaReportes {
        
        private string nombreBeneficiarioField;
        
        private string nombreField;
        
        private string noSocioField;
        
        private string idCoopField;
        
        private string coopField;
        
        private string apoyoFunerarioField;
        
        private string numeroPolizaField;
        
        private string plazaField;
        
        private string sucursalField;
        
        private string numeroReclamoField;
        
        private string idBeneficiarioField;
        
        /// <comentarios/>
        public string NombreBeneficiario {
            get {
                return this.nombreBeneficiarioField;
            }
            set {
                this.nombreBeneficiarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NoSocio {
            get {
                return this.noSocioField;
            }
            set {
                this.noSocioField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCoop {
            get {
                return this.idCoopField;
            }
            set {
                this.idCoopField = value;
            }
        }
        
        /// <comentarios/>
        public string Coop {
            get {
                return this.coopField;
            }
            set {
                this.coopField = value;
            }
        }
        
        /// <comentarios/>
        public string ApoyoFunerario {
            get {
                return this.apoyoFunerarioField;
            }
            set {
                this.apoyoFunerarioField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroPoliza {
            get {
                return this.numeroPolizaField;
            }
            set {
                this.numeroPolizaField = value;
            }
        }
        
        /// <comentarios/>
        public string Plaza {
            get {
                return this.plazaField;
            }
            set {
                this.plazaField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroReclamo {
            get {
                return this.numeroReclamoField;
            }
            set {
                this.numeroReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdBeneficiario {
            get {
                return this.idBeneficiarioField;
            }
            set {
                this.idBeneficiarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class ConsultaContabilidad {
        
        private string plazaField;
        
        private string numeroReclamoField;
        
        private string saldoCaptacionField;
        
        private string saldoColocacionField;
        
        private string saldoAditamentoJField;
        
        private string saldoDobleIField;
        
        private string sumaTotalField;
        
        private string apoyoFunerarioField;
        
        private string aditamentoJuvField;
        
        private System.DateTime fechaActualField;
        
        /// <comentarios/>
        public string Plaza {
            get {
                return this.plazaField;
            }
            set {
                this.plazaField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroReclamo {
            get {
                return this.numeroReclamoField;
            }
            set {
                this.numeroReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoCaptacion {
            get {
                return this.saldoCaptacionField;
            }
            set {
                this.saldoCaptacionField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoColocacion {
            get {
                return this.saldoColocacionField;
            }
            set {
                this.saldoColocacionField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoAditamentoJ {
            get {
                return this.saldoAditamentoJField;
            }
            set {
                this.saldoAditamentoJField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoDobleI {
            get {
                return this.saldoDobleIField;
            }
            set {
                this.saldoDobleIField = value;
            }
        }
        
        /// <comentarios/>
        public string SumaTotal {
            get {
                return this.sumaTotalField;
            }
            set {
                this.sumaTotalField = value;
            }
        }
        
        /// <comentarios/>
        public string ApoyoFunerario {
            get {
                return this.apoyoFunerarioField;
            }
            set {
                this.apoyoFunerarioField = value;
            }
        }
        
        /// <comentarios/>
        public string AditamentoJuv {
            get {
                return this.aditamentoJuvField;
            }
            set {
                this.aditamentoJuvField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaActual {
            get {
                return this.fechaActualField;
            }
            set {
                this.fechaActualField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class DatosAnalisis {
        
        private string ultima_Fecha_LabField;
        
        private string fecha_MuerteField;
        
        private string edadMuerteField;
        
        private string idCausanteField;
        
        private string causa_MuerteField;
        
        private string idFallecimientoField;
        
        private bool menor_AhorradorField;
        
        private string aditamento_JuvField;
        
        /// <comentarios/>
        public string Ultima_Fecha_Lab {
            get {
                return this.ultima_Fecha_LabField;
            }
            set {
                this.ultima_Fecha_LabField = value;
            }
        }
        
        /// <comentarios/>
        public string Fecha_Muerte {
            get {
                return this.fecha_MuerteField;
            }
            set {
                this.fecha_MuerteField = value;
            }
        }
        
        /// <comentarios/>
        public string EdadMuerte {
            get {
                return this.edadMuerteField;
            }
            set {
                this.edadMuerteField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCausante {
            get {
                return this.idCausanteField;
            }
            set {
                this.idCausanteField = value;
            }
        }
        
        /// <comentarios/>
        public string Causa_Muerte {
            get {
                return this.causa_MuerteField;
            }
            set {
                this.causa_MuerteField = value;
            }
        }
        
        /// <comentarios/>
        public string IdFallecimiento {
            get {
                return this.idFallecimientoField;
            }
            set {
                this.idFallecimientoField = value;
            }
        }
        
        /// <comentarios/>
        public bool Menor_Ahorrador {
            get {
                return this.menor_AhorradorField;
            }
            set {
                this.menor_AhorradorField = value;
            }
        }
        
        /// <comentarios/>
        public string Aditamento_Juv {
            get {
                return this.aditamento_JuvField;
            }
            set {
                this.aditamento_JuvField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaBeneficios.asmx")]
    public partial class DatosSocioAlta {
        
        private string numSocioField;
        
        private string sucursalField;
        
        private string nombreField;
        
        private string nombre2Field;
        
        private string apellidoPatField;
        
        private string apellidoMatField;
        
        private string fechaNacField;
        
        private string fechaIngField;
        
        private bool sexoField;
        
        private string ocupacionField;
        
        private string edoCivilField;
        
        private string calleField;
        
        private string numExtField;
        
        private string numIntField;
        
        private string idPaqueteriaField;
        
        private string numeroGuiaField;
        
        private string estadoField;
        
        private string municipioField;
        
        private string coloniaField;
        
        /// <comentarios/>
        public string NumSocio {
            get {
                return this.numSocioField;
            }
            set {
                this.numSocioField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre2 {
            get {
                return this.nombre2Field;
            }
            set {
                this.nombre2Field = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidoPat {
            get {
                return this.apellidoPatField;
            }
            set {
                this.apellidoPatField = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidoMat {
            get {
                return this.apellidoMatField;
            }
            set {
                this.apellidoMatField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaIng {
            get {
                return this.fechaIngField;
            }
            set {
                this.fechaIngField = value;
            }
        }
        
        /// <comentarios/>
        public bool Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        public string Ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
            }
        }
        
        /// <comentarios/>
        public string EdoCivil {
            get {
                return this.edoCivilField;
            }
            set {
                this.edoCivilField = value;
            }
        }
        
        /// <comentarios/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <comentarios/>
        public string NumExt {
            get {
                return this.numExtField;
            }
            set {
                this.numExtField = value;
            }
        }
        
        /// <comentarios/>
        public string NumInt {
            get {
                return this.numIntField;
            }
            set {
                this.numIntField = value;
            }
        }
        
        /// <comentarios/>
        public string IdPaqueteria {
            get {
                return this.idPaqueteriaField;
            }
            set {
                this.idPaqueteriaField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroGuia {
            get {
                return this.numeroGuiaField;
            }
            set {
                this.numeroGuiaField = value;
            }
        }
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <comentarios/>
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CargaDatosSocioCompletedEventHandler(object sender, CargaDatosSocioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaDatosSocioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaDatosSocioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosSocio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosSocio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CargaDatosSocioAltaCompletedEventHandler(object sender, CargaDatosSocioAltaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaDatosSocioAltaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaDatosSocioAltaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosSocioAlta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosSocioAlta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CargaDatosAnalisisCompletedEventHandler(object sender, CargaDatosAnalisisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaDatosAnalisisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaDatosAnalisisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosAnalisis Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosAnalisis)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultasContabilidadCompletedEventHandler(object sender, ConsultasContabilidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultasContabilidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultasContabilidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaContabilidad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaContabilidad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaReportesBeneficiosCompletedEventHandler(object sender, ConsultaReportesBeneficiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReportesBeneficiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaReportesBeneficiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaReportes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaReportes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultasSaldoTotalCaptacionCompletedEventHandler(object sender, ConsultasSaldoTotalCaptacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultasSaldoTotalCaptacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultasSaldoTotalCaptacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaSaldoTotalCaptacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaSaldoTotalCaptacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultasSaldoTotalColocacionCompletedEventHandler(object sender, ConsultasSaldoTotalColocacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultasSaldoTotalColocacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultasSaldoTotalColocacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaSaldoTotalColocacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaSaldoTotalColocacion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591