//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.586.
// 
#pragma warning disable 1591

namespace SDA.Controles {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsControlesAccesoSoap", Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class wsControlesAcceso : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActualizaPassOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstatusUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesencriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertLogDanosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsignarRolUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuitarRolUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaRolesXUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPermisosXRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPermisosXUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaUsuariosEspecificosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDatUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPermisoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPermisosXRolOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsControlesAcceso() {
            this.Url = global::SDA.Properties.Settings.Default.SDA_Controles_wsControlesAcceso;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActualizaPassCompletedEventHandler ActualizaPassCompleted;
        
        /// <remarks/>
        public event EstatusUserCompletedEventHandler EstatusUserCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event EncriptarCompletedEventHandler EncriptarCompleted;
        
        /// <remarks/>
        public event DesencriptarCompletedEventHandler DesencriptarCompleted;
        
        /// <remarks/>
        public event InsertLogDanosCompletedEventHandler InsertLogDanosCompleted;
        
        /// <remarks/>
        public event GenPasswordCompletedEventHandler GenPasswordCompleted;
        
        /// <remarks/>
        public event InsertUserCompletedEventHandler InsertUserCompleted;
        
        /// <remarks/>
        public event AsignarRolUserCompletedEventHandler AsignarRolUserCompleted;
        
        /// <remarks/>
        public event QuitarRolUserCompletedEventHandler QuitarRolUserCompleted;
        
        /// <remarks/>
        public event ConsultaRolesCompletedEventHandler ConsultaRolesCompleted;
        
        /// <remarks/>
        public event ConsultaRolesXUserCompletedEventHandler ConsultaRolesXUserCompleted;
        
        /// <remarks/>
        public event ConsultaPermisosXRolCompletedEventHandler ConsultaPermisosXRolCompleted;
        
        /// <remarks/>
        public event ConsultaPermisosXUserCompletedEventHandler ConsultaPermisosXUserCompleted;
        
        /// <remarks/>
        public event ConsultaUsuariosCompletedEventHandler ConsultaUsuariosCompleted;
        
        /// <remarks/>
        public event ConsultaUsuariosEspecificosCompletedEventHandler ConsultaUsuariosEspecificosCompleted;
        
        /// <remarks/>
        public event ConsultaDatUsuarioCompletedEventHandler ConsultaDatUsuarioCompleted;
        
        /// <remarks/>
        public event InsertRolCompletedEventHandler InsertRolCompleted;
        
        /// <remarks/>
        public event InsertPermisoCompletedEventHandler InsertPermisoCompleted;
        
        /// <remarks/>
        public event InsertPermisosXRolCompletedEventHandler InsertPermisosXRolCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ActualizaPass", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error ActualizaPass(int IdUser, string User, string OPass, string Pass) {
            object[] results = this.Invoke("ActualizaPass", new object[] {
                        IdUser,
                        User,
                        OPass,
                        Pass});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaPassAsync(int IdUser, string User, string OPass, string Pass) {
            this.ActualizaPassAsync(IdUser, User, OPass, Pass, null);
        }
        
        /// <remarks/>
        public void ActualizaPassAsync(int IdUser, string User, string OPass, string Pass, object userState) {
            if ((this.ActualizaPassOperationCompleted == null)) {
                this.ActualizaPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaPassOperationCompleted);
            }
            this.InvokeAsync("ActualizaPass", new object[] {
                        IdUser,
                        User,
                        OPass,
                        Pass}, this.ActualizaPassOperationCompleted, userState);
        }
        
        private void OnActualizaPassOperationCompleted(object arg) {
            if ((this.ActualizaPassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaPassCompleted(this, new ActualizaPassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/EstatusUser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EstatusUser(int IdUser, int Estatus) {
            this.Invoke("EstatusUser", new object[] {
                        IdUser,
                        Estatus});
        }
        
        /// <remarks/>
        public void EstatusUserAsync(int IdUser, int Estatus) {
            this.EstatusUserAsync(IdUser, Estatus, null);
        }
        
        /// <remarks/>
        public void EstatusUserAsync(int IdUser, int Estatus, object userState) {
            if ((this.EstatusUserOperationCompleted == null)) {
                this.EstatusUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstatusUserOperationCompleted);
            }
            this.InvokeAsync("EstatusUser", new object[] {
                        IdUser,
                        Estatus}, this.EstatusUserOperationCompleted, userState);
        }
        
        private void OnEstatusUserOperationCompleted(object arg) {
            if ((this.EstatusUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstatusUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ValidateUser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Variables ValidateUser(string userName, string passWord) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        userName,
                        passWord});
            return ((Variables)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string userName, string passWord) {
            this.ValidateUserAsync(userName, passWord, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string userName, string passWord, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        userName,
                        passWord}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/Encriptar", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Encriptar(string texto) {
            object[] results = this.Invoke("Encriptar", new object[] {
                        texto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncriptarAsync(string texto) {
            this.EncriptarAsync(texto, null);
        }
        
        /// <remarks/>
        public void EncriptarAsync(string texto, object userState) {
            if ((this.EncriptarOperationCompleted == null)) {
                this.EncriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncriptarOperationCompleted);
            }
            this.InvokeAsync("Encriptar", new object[] {
                        texto}, this.EncriptarOperationCompleted, userState);
        }
        
        private void OnEncriptarOperationCompleted(object arg) {
            if ((this.EncriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncriptarCompleted(this, new EncriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/Desencriptar", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Desencriptar(string textoEncriptado) {
            object[] results = this.Invoke("Desencriptar", new object[] {
                        textoEncriptado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesencriptarAsync(string textoEncriptado) {
            this.DesencriptarAsync(textoEncriptado, null);
        }
        
        /// <remarks/>
        public void DesencriptarAsync(string textoEncriptado, object userState) {
            if ((this.DesencriptarOperationCompleted == null)) {
                this.DesencriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesencriptarOperationCompleted);
            }
            this.InvokeAsync("Desencriptar", new object[] {
                        textoEncriptado}, this.DesencriptarOperationCompleted, userState);
        }
        
        private void OnDesencriptarOperationCompleted(object arg) {
            if ((this.DesencriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesencriptarCompleted(this, new DesencriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/InsertLogDanos", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertLogDanos(int Usuario, int Mensaje, string Detalle) {
            object[] results = this.Invoke("InsertLogDanos", new object[] {
                        Usuario,
                        Mensaje,
                        Detalle});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertLogDanosAsync(int Usuario, int Mensaje, string Detalle) {
            this.InsertLogDanosAsync(Usuario, Mensaje, Detalle, null);
        }
        
        /// <remarks/>
        public void InsertLogDanosAsync(int Usuario, int Mensaje, string Detalle, object userState) {
            if ((this.InsertLogDanosOperationCompleted == null)) {
                this.InsertLogDanosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertLogDanosOperationCompleted);
            }
            this.InvokeAsync("InsertLogDanos", new object[] {
                        Usuario,
                        Mensaje,
                        Detalle}, this.InsertLogDanosOperationCompleted, userState);
        }
        
        private void OnInsertLogDanosOperationCompleted(object arg) {
            if ((this.InsertLogDanosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertLogDanosCompleted(this, new InsertLogDanosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/GenPassword", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenPassword(int longitud) {
            object[] results = this.Invoke("GenPassword", new object[] {
                        longitud});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenPasswordAsync(int longitud) {
            this.GenPasswordAsync(longitud, null);
        }
        
        /// <remarks/>
        public void GenPasswordAsync(int longitud, object userState) {
            if ((this.GenPasswordOperationCompleted == null)) {
                this.GenPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenPasswordOperationCompleted);
            }
            this.InvokeAsync("GenPassword", new object[] {
                        longitud}, this.GenPasswordOperationCompleted, userState);
        }
        
        private void OnGenPasswordOperationCompleted(object arg) {
            if ((this.GenPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenPasswordCompleted(this, new GenPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/InsertUser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertUser(string Nombre, string Nombre_2, string Apellido_Pat, string Apellido_Mat, int IdSuc, string Correo, string Usuario, string Pass, bool Activo, int IdUser) {
            object[] results = this.Invoke("InsertUser", new object[] {
                        Nombre,
                        Nombre_2,
                        Apellido_Pat,
                        Apellido_Mat,
                        IdSuc,
                        Correo,
                        Usuario,
                        Pass,
                        Activo,
                        IdUser});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertUserAsync(string Nombre, string Nombre_2, string Apellido_Pat, string Apellido_Mat, int IdSuc, string Correo, string Usuario, string Pass, bool Activo, int IdUser) {
            this.InsertUserAsync(Nombre, Nombre_2, Apellido_Pat, Apellido_Mat, IdSuc, Correo, Usuario, Pass, Activo, IdUser, null);
        }
        
        /// <remarks/>
        public void InsertUserAsync(string Nombre, string Nombre_2, string Apellido_Pat, string Apellido_Mat, int IdSuc, string Correo, string Usuario, string Pass, bool Activo, int IdUser, object userState) {
            if ((this.InsertUserOperationCompleted == null)) {
                this.InsertUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUserOperationCompleted);
            }
            this.InvokeAsync("InsertUser", new object[] {
                        Nombre,
                        Nombre_2,
                        Apellido_Pat,
                        Apellido_Mat,
                        IdSuc,
                        Correo,
                        Usuario,
                        Pass,
                        Activo,
                        IdUser}, this.InsertUserOperationCompleted, userState);
        }
        
        private void OnInsertUserOperationCompleted(object arg) {
            if ((this.InsertUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUserCompleted(this, new InsertUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/AsignarRolUser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error AsignarRolUser(int IdUser, int IdRol) {
            object[] results = this.Invoke("AsignarRolUser", new object[] {
                        IdUser,
                        IdRol});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void AsignarRolUserAsync(int IdUser, int IdRol) {
            this.AsignarRolUserAsync(IdUser, IdRol, null);
        }
        
        /// <remarks/>
        public void AsignarRolUserAsync(int IdUser, int IdRol, object userState) {
            if ((this.AsignarRolUserOperationCompleted == null)) {
                this.AsignarRolUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsignarRolUserOperationCompleted);
            }
            this.InvokeAsync("AsignarRolUser", new object[] {
                        IdUser,
                        IdRol}, this.AsignarRolUserOperationCompleted, userState);
        }
        
        private void OnAsignarRolUserOperationCompleted(object arg) {
            if ((this.AsignarRolUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsignarRolUserCompleted(this, new AsignarRolUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/QuitarRolUser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error QuitarRolUser(int IdUser, int IdRol) {
            object[] results = this.Invoke("QuitarRolUser", new object[] {
                        IdUser,
                        IdRol});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void QuitarRolUserAsync(int IdUser, int IdRol) {
            this.QuitarRolUserAsync(IdUser, IdRol, null);
        }
        
        /// <remarks/>
        public void QuitarRolUserAsync(int IdUser, int IdRol, object userState) {
            if ((this.QuitarRolUserOperationCompleted == null)) {
                this.QuitarRolUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuitarRolUserOperationCompleted);
            }
            this.InvokeAsync("QuitarRolUser", new object[] {
                        IdUser,
                        IdRol}, this.QuitarRolUserOperationCompleted, userState);
        }
        
        private void OnQuitarRolUserOperationCompleted(object arg) {
            if ((this.QuitarRolUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuitarRolUserCompleted(this, new QuitarRolUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaRoles", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Roles[] ConsultaRoles(int IdSistema) {
            object[] results = this.Invoke("ConsultaRoles", new object[] {
                        IdSistema});
            return ((Roles[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaRolesAsync(int IdSistema) {
            this.ConsultaRolesAsync(IdSistema, null);
        }
        
        /// <remarks/>
        public void ConsultaRolesAsync(int IdSistema, object userState) {
            if ((this.ConsultaRolesOperationCompleted == null)) {
                this.ConsultaRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaRolesOperationCompleted);
            }
            this.InvokeAsync("ConsultaRoles", new object[] {
                        IdSistema}, this.ConsultaRolesOperationCompleted, userState);
        }
        
        private void OnConsultaRolesOperationCompleted(object arg) {
            if ((this.ConsultaRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaRolesCompleted(this, new ConsultaRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaRolesXU" +
            "ser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Roles[] ConsultaRolesXUser(int IdUser, int IdSistema) {
            object[] results = this.Invoke("ConsultaRolesXUser", new object[] {
                        IdUser,
                        IdSistema});
            return ((Roles[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaRolesXUserAsync(int IdUser, int IdSistema) {
            this.ConsultaRolesXUserAsync(IdUser, IdSistema, null);
        }
        
        /// <remarks/>
        public void ConsultaRolesXUserAsync(int IdUser, int IdSistema, object userState) {
            if ((this.ConsultaRolesXUserOperationCompleted == null)) {
                this.ConsultaRolesXUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaRolesXUserOperationCompleted);
            }
            this.InvokeAsync("ConsultaRolesXUser", new object[] {
                        IdUser,
                        IdSistema}, this.ConsultaRolesXUserOperationCompleted, userState);
        }
        
        private void OnConsultaRolesXUserOperationCompleted(object arg) {
            if ((this.ConsultaRolesXUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaRolesXUserCompleted(this, new ConsultaRolesXUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaPermiso" +
            "sXRol", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permisos[] ConsultaPermisosXRol(int IdRol) {
            object[] results = this.Invoke("ConsultaPermisosXRol", new object[] {
                        IdRol});
            return ((Permisos[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPermisosXRolAsync(int IdRol) {
            this.ConsultaPermisosXRolAsync(IdRol, null);
        }
        
        /// <remarks/>
        public void ConsultaPermisosXRolAsync(int IdRol, object userState) {
            if ((this.ConsultaPermisosXRolOperationCompleted == null)) {
                this.ConsultaPermisosXRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPermisosXRolOperationCompleted);
            }
            this.InvokeAsync("ConsultaPermisosXRol", new object[] {
                        IdRol}, this.ConsultaPermisosXRolOperationCompleted, userState);
        }
        
        private void OnConsultaPermisosXRolOperationCompleted(object arg) {
            if ((this.ConsultaPermisosXRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPermisosXRolCompleted(this, new ConsultaPermisosXRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaPermiso" +
            "sXUser", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permisos[] ConsultaPermisosXUser(int IdUser) {
            object[] results = this.Invoke("ConsultaPermisosXUser", new object[] {
                        IdUser});
            return ((Permisos[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPermisosXUserAsync(int IdUser) {
            this.ConsultaPermisosXUserAsync(IdUser, null);
        }
        
        /// <remarks/>
        public void ConsultaPermisosXUserAsync(int IdUser, object userState) {
            if ((this.ConsultaPermisosXUserOperationCompleted == null)) {
                this.ConsultaPermisosXUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPermisosXUserOperationCompleted);
            }
            this.InvokeAsync("ConsultaPermisosXUser", new object[] {
                        IdUser}, this.ConsultaPermisosXUserOperationCompleted, userState);
        }
        
        private void OnConsultaPermisosXUserOperationCompleted(object arg) {
            if ((this.ConsultaPermisosXUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPermisosXUserCompleted(this, new ConsultaPermisosXUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaUsuario" +
            "s", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario_Sim[] ConsultaUsuarios() {
            object[] results = this.Invoke("ConsultaUsuarios", new object[0]);
            return ((Usuario_Sim[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaUsuariosAsync() {
            this.ConsultaUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaUsuariosAsync(object userState) {
            if ((this.ConsultaUsuariosOperationCompleted == null)) {
                this.ConsultaUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaUsuariosOperationCompleted);
            }
            this.InvokeAsync("ConsultaUsuarios", new object[0], this.ConsultaUsuariosOperationCompleted, userState);
        }
        
        private void OnConsultaUsuariosOperationCompleted(object arg) {
            if ((this.ConsultaUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaUsuariosCompleted(this, new ConsultaUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaUsuario" +
            "sEspecificos", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario_Sim[] ConsultaUsuariosEspecificos(string Coop) {
            object[] results = this.Invoke("ConsultaUsuariosEspecificos", new object[] {
                        Coop});
            return ((Usuario_Sim[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaUsuariosEspecificosAsync(string Coop) {
            this.ConsultaUsuariosEspecificosAsync(Coop, null);
        }
        
        /// <remarks/>
        public void ConsultaUsuariosEspecificosAsync(string Coop, object userState) {
            if ((this.ConsultaUsuariosEspecificosOperationCompleted == null)) {
                this.ConsultaUsuariosEspecificosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaUsuariosEspecificosOperationCompleted);
            }
            this.InvokeAsync("ConsultaUsuariosEspecificos", new object[] {
                        Coop}, this.ConsultaUsuariosEspecificosOperationCompleted, userState);
        }
        
        private void OnConsultaUsuariosEspecificosOperationCompleted(object arg) {
            if ((this.ConsultaUsuariosEspecificosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaUsuariosEspecificosCompleted(this, new ConsultaUsuariosEspecificosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/ConsultaDatUsua" +
            "rio", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario_Com ConsultaDatUsuario(int IdUser) {
            object[] results = this.Invoke("ConsultaDatUsuario", new object[] {
                        IdUser});
            return ((Usuario_Com)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDatUsuarioAsync(int IdUser) {
            this.ConsultaDatUsuarioAsync(IdUser, null);
        }
        
        /// <remarks/>
        public void ConsultaDatUsuarioAsync(int IdUser, object userState) {
            if ((this.ConsultaDatUsuarioOperationCompleted == null)) {
                this.ConsultaDatUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDatUsuarioOperationCompleted);
            }
            this.InvokeAsync("ConsultaDatUsuario", new object[] {
                        IdUser}, this.ConsultaDatUsuarioOperationCompleted, userState);
        }
        
        private void OnConsultaDatUsuarioOperationCompleted(object arg) {
            if ((this.ConsultaDatUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDatUsuarioCompleted(this, new ConsultaDatUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/InsertRol", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertRol(int IdSistema, string Rol) {
            object[] results = this.Invoke("InsertRol", new object[] {
                        IdSistema,
                        Rol});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRolAsync(int IdSistema, string Rol) {
            this.InsertRolAsync(IdSistema, Rol, null);
        }
        
        /// <remarks/>
        public void InsertRolAsync(int IdSistema, string Rol, object userState) {
            if ((this.InsertRolOperationCompleted == null)) {
                this.InsertRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRolOperationCompleted);
            }
            this.InvokeAsync("InsertRol", new object[] {
                        IdSistema,
                        Rol}, this.InsertRolOperationCompleted, userState);
        }
        
        private void OnInsertRolOperationCompleted(object arg) {
            if ((this.InsertRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRolCompleted(this, new InsertRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/InsertPermiso", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertPermiso(string Permiso) {
            object[] results = this.Invoke("InsertPermiso", new object[] {
                        Permiso});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPermisoAsync(string Permiso) {
            this.InsertPermisoAsync(Permiso, null);
        }
        
        /// <remarks/>
        public void InsertPermisoAsync(string Permiso, object userState) {
            if ((this.InsertPermisoOperationCompleted == null)) {
                this.InsertPermisoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPermisoOperationCompleted);
            }
            this.InvokeAsync("InsertPermiso", new object[] {
                        Permiso}, this.InsertPermisoOperationCompleted, userState);
        }
        
        private void OnInsertPermisoOperationCompleted(object arg) {
            if ((this.InsertPermisoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPermisoCompleted(this, new InsertPermisoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx/InsertPermisosX" +
            "Rol", RequestNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", ResponseNamespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error InsertPermisosXRol(int IdRol, int IdPermiso) {
            object[] results = this.Invoke("InsertPermisosXRol", new object[] {
                        IdRol,
                        IdPermiso});
            return ((Error)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPermisosXRolAsync(int IdRol, int IdPermiso) {
            this.InsertPermisosXRolAsync(IdRol, IdPermiso, null);
        }
        
        /// <remarks/>
        public void InsertPermisosXRolAsync(int IdRol, int IdPermiso, object userState) {
            if ((this.InsertPermisosXRolOperationCompleted == null)) {
                this.InsertPermisosXRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPermisosXRolOperationCompleted);
            }
            this.InvokeAsync("InsertPermisosXRol", new object[] {
                        IdRol,
                        IdPermiso}, this.InsertPermisosXRolOperationCompleted, userState);
        }
        
        private void OnInsertPermisosXRolOperationCompleted(object arg) {
            if ((this.InsertPermisosXRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPermisosXRolCompleted(this, new InsertPermisosXRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class Error {
        
        private string mensajeField;
        
        private bool valorField;
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public bool Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class Usuario_Com {
        
        private Usuario_Sim usuario_SimField;
        
        private string nombre_1Field;
        
        private string nombre_2Field;
        
        private string apellido_PatField;
        
        private string apellido_MatField;
        
        private int id_CoopField;
        
        private int id_PlazaField;
        
        private int id_SucursalField;
        
        private string correoField;
        
        private bool activoField;
        
        private int estatusField;
        
        /// <comentarios/>
        public Usuario_Sim Usuario_Sim {
            get {
                return this.usuario_SimField;
            }
            set {
                this.usuario_SimField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre_1 {
            get {
                return this.nombre_1Field;
            }
            set {
                this.nombre_1Field = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre_2 {
            get {
                return this.nombre_2Field;
            }
            set {
                this.nombre_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Apellido_Pat {
            get {
                return this.apellido_PatField;
            }
            set {
                this.apellido_PatField = value;
            }
        }
        
        /// <comentarios/>
        public string Apellido_Mat {
            get {
                return this.apellido_MatField;
            }
            set {
                this.apellido_MatField = value;
            }
        }
        
        /// <comentarios/>
        public int Id_Coop {
            get {
                return this.id_CoopField;
            }
            set {
                this.id_CoopField = value;
            }
        }
        
        /// <comentarios/>
        public int Id_Plaza {
            get {
                return this.id_PlazaField;
            }
            set {
                this.id_PlazaField = value;
            }
        }
        
        /// <comentarios/>
        public int Id_Sucursal {
            get {
                return this.id_SucursalField;
            }
            set {
                this.id_SucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <comentarios/>
        public bool Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <comentarios/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class Usuario_Sim {
        
        private int id_UsuarioField;
        
        private string nombreField;
        
        private string coopField;
        
        private string plazaField;
        
        private string sucursalField;
        
        private string usuarioField;
        
        private string estado_UserField;
        
        /// <comentarios/>
        public int Id_Usuario {
            get {
                return this.id_UsuarioField;
            }
            set {
                this.id_UsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Coop {
            get {
                return this.coopField;
            }
            set {
                this.coopField = value;
            }
        }
        
        /// <comentarios/>
        public string Plaza {
            get {
                return this.plazaField;
            }
            set {
                this.plazaField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Estado_User {
            get {
                return this.estado_UserField;
            }
            set {
                this.estado_UserField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class Permisos {
        
        private int idPermisoField;
        
        private string permisoField;
        
        /// <comentarios/>
        public int IdPermiso {
            get {
                return this.idPermisoField;
            }
            set {
                this.idPermisoField = value;
            }
        }
        
        /// <comentarios/>
        public string Permiso {
            get {
                return this.permisoField;
            }
            set {
                this.permisoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class Roles {
        
        private int idRolField;
        
        private string rolField;
        
        /// <comentarios/>
        public int IdRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
            }
        }
        
        /// <comentarios/>
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Error", Namespace="http://qa.prybe.coop/WSPrybeCPM/wspcpm/wsPrybeCPM.asmx")]
    public partial class Error1 {
        
        private bool valorField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public bool Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seguros.prybe.coop/WSPrybeBDa/wspbd/wsControlesAcceso.asmx")]
    public partial class Variables {
        
        private int[] listaPermisosField;
        
        private int ejecutField;
        
        private int estatField;
        
        private bool activField;
        
        private bool accessField;
        
        private string nombreCompletoField;
        
        private string correoField;
        
        private int idSucursalField;
        
        private int idCoopField;
        
        private Error1 errorField;
        
        /// <comentarios/>
        public int[] ListaPermisos {
            get {
                return this.listaPermisosField;
            }
            set {
                this.listaPermisosField = value;
            }
        }
        
        /// <comentarios/>
        public int Ejecut {
            get {
                return this.ejecutField;
            }
            set {
                this.ejecutField = value;
            }
        }
        
        /// <comentarios/>
        public int Estat {
            get {
                return this.estatField;
            }
            set {
                this.estatField = value;
            }
        }
        
        /// <comentarios/>
        public bool Activ {
            get {
                return this.activField;
            }
            set {
                this.activField = value;
            }
        }
        
        /// <comentarios/>
        public bool Access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <comentarios/>
        public int IdSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
        
        /// <comentarios/>
        public int IdCoop {
            get {
                return this.idCoopField;
            }
            set {
                this.idCoopField = value;
            }
        }
        
        /// <comentarios/>
        public Error1 Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizaPassCompletedEventHandler(object sender, ActualizaPassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EstatusUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Variables Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Variables)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EncriptarCompletedEventHandler(object sender, EncriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DesencriptarCompletedEventHandler(object sender, DesencriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesencriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesencriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertLogDanosCompletedEventHandler(object sender, InsertLogDanosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertLogDanosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertLogDanosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GenPasswordCompletedEventHandler(object sender, GenPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertUserCompletedEventHandler(object sender, InsertUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AsignarRolUserCompletedEventHandler(object sender, AsignarRolUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsignarRolUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsignarRolUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QuitarRolUserCompletedEventHandler(object sender, QuitarRolUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuitarRolUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuitarRolUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaRolesCompletedEventHandler(object sender, ConsultaRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Roles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Roles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaRolesXUserCompletedEventHandler(object sender, ConsultaRolesXUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaRolesXUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaRolesXUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Roles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Roles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaPermisosXRolCompletedEventHandler(object sender, ConsultaPermisosXRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPermisosXRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPermisosXRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permisos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permisos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaPermisosXUserCompletedEventHandler(object sender, ConsultaPermisosXUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPermisosXUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPermisosXUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permisos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permisos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaUsuariosCompletedEventHandler(object sender, ConsultaUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario_Sim[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario_Sim[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaUsuariosEspecificosCompletedEventHandler(object sender, ConsultaUsuariosEspecificosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaUsuariosEspecificosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaUsuariosEspecificosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario_Sim[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario_Sim[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaDatUsuarioCompletedEventHandler(object sender, ConsultaDatUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDatUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDatUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario_Com Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario_Com)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertRolCompletedEventHandler(object sender, InsertRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertPermisoCompletedEventHandler(object sender, InsertPermisoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPermisoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPermisoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertPermisosXRolCompletedEventHandler(object sender, InsertPermisosXRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPermisosXRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPermisosXRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591