//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18213
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18213.
// 
#pragma warning disable 1591

namespace SDA.wsConsultasMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsConsultasSoap", Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class wsConsultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaDatosPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaIdSucPrybeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPolizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaParentescoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPolizasSocioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CURPExisteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBeneficiariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnIdSocioMAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnDatMenorAHOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsConsultas() {
            this.Url = global::SDA.Properties.Settings.Default.SDA_wsConsultasMS_wsConsultas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaDatosPagoCompletedEventHandler ConsultaDatosPagoCompleted;
        
        /// <remarks/>
        public event ConsultaIdSucPrybeCompletedEventHandler ConsultaIdSucPrybeCompleted;
        
        /// <remarks/>
        public event ConsultaPolizaCompletedEventHandler ConsultaPolizaCompleted;
        
        /// <remarks/>
        public event ConsultaParentescoCompletedEventHandler ConsultaParentescoCompleted;
        
        /// <remarks/>
        public event ConsultaPolizasSocioCompletedEventHandler ConsultaPolizasSocioCompleted;
        
        /// <remarks/>
        public event CURPExisteCompletedEventHandler CURPExisteCompleted;
        
        /// <remarks/>
        public event ConsultaBeneficiariosCompletedEventHandler ConsultaBeneficiariosCompleted;
        
        /// <remarks/>
        public event ReturnIdSocioMACompletedEventHandler ReturnIdSocioMACompleted;
        
        /// <remarks/>
        public event ReturnDatMenorAHCompletedEventHandler ReturnDatMenorAHCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ConsultaDatosPago", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatosPago ConsultaDatosPago(int IdSiniestro) {
            object[] results = this.Invoke("ConsultaDatosPago", new object[] {
                        IdSiniestro});
            return ((DatosPago)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDatosPagoAsync(int IdSiniestro) {
            this.ConsultaDatosPagoAsync(IdSiniestro, null);
        }
        
        /// <remarks/>
        public void ConsultaDatosPagoAsync(int IdSiniestro, object userState) {
            if ((this.ConsultaDatosPagoOperationCompleted == null)) {
                this.ConsultaDatosPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDatosPagoOperationCompleted);
            }
            this.InvokeAsync("ConsultaDatosPago", new object[] {
                        IdSiniestro}, this.ConsultaDatosPagoOperationCompleted, userState);
        }
        
        private void OnConsultaDatosPagoOperationCompleted(object arg) {
            if ((this.ConsultaDatosPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDatosPagoCompleted(this, new ConsultaDatosPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ConsultaIdSucPrybe", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sucursal ConsultaIdSucPrybe(int IdSucursal) {
            object[] results = this.Invoke("ConsultaIdSucPrybe", new object[] {
                        IdSucursal});
            return ((Sucursal)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaIdSucPrybeAsync(int IdSucursal) {
            this.ConsultaIdSucPrybeAsync(IdSucursal, null);
        }
        
        /// <remarks/>
        public void ConsultaIdSucPrybeAsync(int IdSucursal, object userState) {
            if ((this.ConsultaIdSucPrybeOperationCompleted == null)) {
                this.ConsultaIdSucPrybeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaIdSucPrybeOperationCompleted);
            }
            this.InvokeAsync("ConsultaIdSucPrybe", new object[] {
                        IdSucursal}, this.ConsultaIdSucPrybeOperationCompleted, userState);
        }
        
        private void OnConsultaIdSucPrybeOperationCompleted(object arg) {
            if ((this.ConsultaIdSucPrybeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaIdSucPrybeCompleted(this, new ConsultaIdSucPrybeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ConsultaPoliza", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaPoliza(int IdEmision) {
            object[] results = this.Invoke("ConsultaPoliza", new object[] {
                        IdEmision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPolizaAsync(int IdEmision) {
            this.ConsultaPolizaAsync(IdEmision, null);
        }
        
        /// <remarks/>
        public void ConsultaPolizaAsync(int IdEmision, object userState) {
            if ((this.ConsultaPolizaOperationCompleted == null)) {
                this.ConsultaPolizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPolizaOperationCompleted);
            }
            this.InvokeAsync("ConsultaPoliza", new object[] {
                        IdEmision}, this.ConsultaPolizaOperationCompleted, userState);
        }
        
        private void OnConsultaPolizaOperationCompleted(object arg) {
            if ((this.ConsultaPolizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPolizaCompleted(this, new ConsultaPolizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ConsultaParentesco", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Parentesco[] ConsultaParentesco() {
            object[] results = this.Invoke("ConsultaParentesco", new object[0]);
            return ((Parentesco[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaParentescoAsync() {
            this.ConsultaParentescoAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaParentescoAsync(object userState) {
            if ((this.ConsultaParentescoOperationCompleted == null)) {
                this.ConsultaParentescoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaParentescoOperationCompleted);
            }
            this.InvokeAsync("ConsultaParentesco", new object[0], this.ConsultaParentescoOperationCompleted, userState);
        }
        
        private void OnConsultaParentescoOperationCompleted(object arg) {
            if ((this.ConsultaParentescoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaParentescoCompleted(this, new ConsultaParentescoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ConsultaPolizasSocio", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Poliza[] ConsultaPolizasSocio(int IdCoop, string NoSocio) {
            object[] results = this.Invoke("ConsultaPolizasSocio", new object[] {
                        IdCoop,
                        NoSocio});
            return ((Poliza[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPolizasSocioAsync(int IdCoop, string NoSocio) {
            this.ConsultaPolizasSocioAsync(IdCoop, NoSocio, null);
        }
        
        /// <remarks/>
        public void ConsultaPolizasSocioAsync(int IdCoop, string NoSocio, object userState) {
            if ((this.ConsultaPolizasSocioOperationCompleted == null)) {
                this.ConsultaPolizasSocioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPolizasSocioOperationCompleted);
            }
            this.InvokeAsync("ConsultaPolizasSocio", new object[] {
                        IdCoop,
                        NoSocio}, this.ConsultaPolizasSocioOperationCompleted, userState);
        }
        
        private void OnConsultaPolizasSocioOperationCompleted(object arg) {
            if ((this.ConsultaPolizasSocioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPolizasSocioCompleted(this, new ConsultaPolizasSocioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/CURPExiste", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CURP CURPExiste(string CURP) {
            object[] results = this.Invoke("CURPExiste", new object[] {
                        CURP});
            return ((CURP)(results[0]));
        }
        
        /// <remarks/>
        public void CURPExisteAsync(string CURP) {
            this.CURPExisteAsync(CURP, null);
        }
        
        /// <remarks/>
        public void CURPExisteAsync(string CURP, object userState) {
            if ((this.CURPExisteOperationCompleted == null)) {
                this.CURPExisteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCURPExisteOperationCompleted);
            }
            this.InvokeAsync("CURPExiste", new object[] {
                        CURP}, this.CURPExisteOperationCompleted, userState);
        }
        
        private void OnCURPExisteOperationCompleted(object arg) {
            if ((this.CURPExisteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CURPExisteCompleted(this, new CURPExisteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ConsultaBeneficiarios", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Beneficiario[] ConsultaBeneficiarios(int IdEmision, string SumAseg) {
            object[] results = this.Invoke("ConsultaBeneficiarios", new object[] {
                        IdEmision,
                        SumAseg});
            return ((Beneficiario[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBeneficiariosAsync(int IdEmision, string SumAseg) {
            this.ConsultaBeneficiariosAsync(IdEmision, SumAseg, null);
        }
        
        /// <remarks/>
        public void ConsultaBeneficiariosAsync(int IdEmision, string SumAseg, object userState) {
            if ((this.ConsultaBeneficiariosOperationCompleted == null)) {
                this.ConsultaBeneficiariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBeneficiariosOperationCompleted);
            }
            this.InvokeAsync("ConsultaBeneficiarios", new object[] {
                        IdEmision,
                        SumAseg}, this.ConsultaBeneficiariosOperationCompleted, userState);
        }
        
        private void OnConsultaBeneficiariosOperationCompleted(object arg) {
            if ((this.ConsultaBeneficiariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBeneficiariosCompleted(this, new ConsultaBeneficiariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ReturnIdSocioMA", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IdSocioMA ReturnIdSocioMA(int IdSucursal, string NoSocioMA) {
            object[] results = this.Invoke("ReturnIdSocioMA", new object[] {
                        IdSucursal,
                        NoSocioMA});
            return ((IdSocioMA)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnIdSocioMAAsync(int IdSucursal, string NoSocioMA) {
            this.ReturnIdSocioMAAsync(IdSucursal, NoSocioMA, null);
        }
        
        /// <remarks/>
        public void ReturnIdSocioMAAsync(int IdSucursal, string NoSocioMA, object userState) {
            if ((this.ReturnIdSocioMAOperationCompleted == null)) {
                this.ReturnIdSocioMAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnIdSocioMAOperationCompleted);
            }
            this.InvokeAsync("ReturnIdSocioMA", new object[] {
                        IdSucursal,
                        NoSocioMA}, this.ReturnIdSocioMAOperationCompleted, userState);
        }
        
        private void OnReturnIdSocioMAOperationCompleted(object arg) {
            if ((this.ReturnIdSocioMACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnIdSocioMACompleted(this, new ReturnIdSocioMACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx/ReturnDatMenorAH", RequestNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenorAH ReturnDatMenorAH(string NoSocioMA, int IdCoop) {
            object[] results = this.Invoke("ReturnDatMenorAH", new object[] {
                        NoSocioMA,
                        IdCoop});
            return ((MenorAH)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnDatMenorAHAsync(string NoSocioMA, int IdCoop) {
            this.ReturnDatMenorAHAsync(NoSocioMA, IdCoop, null);
        }
        
        /// <remarks/>
        public void ReturnDatMenorAHAsync(string NoSocioMA, int IdCoop, object userState) {
            if ((this.ReturnDatMenorAHOperationCompleted == null)) {
                this.ReturnDatMenorAHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnDatMenorAHOperationCompleted);
            }
            this.InvokeAsync("ReturnDatMenorAH", new object[] {
                        NoSocioMA,
                        IdCoop}, this.ReturnDatMenorAHOperationCompleted, userState);
        }
        
        private void OnReturnDatMenorAHOperationCompleted(object arg) {
            if ((this.ReturnDatMenorAHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnDatMenorAHCompleted(this, new ReturnDatMenorAHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class DatosPago {
        
        private string noChequeField;
        
        private string fechaPagoField;
        
        /// <comentarios/>
        public string NoCheque {
            get {
                return this.noChequeField;
            }
            set {
                this.noChequeField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class MenorAH {
        
        private string nombreField;
        
        private string nombre2Field;
        
        private string apePatField;
        
        private string apeMatField;
        
        private string correoField;
        
        private string fechaNacField;
        
        private string fechaIngField;
        
        private string cURPField;
        
        private int idCoopField;
        
        private int idPlazaField;
        
        private int idSucursalField;
        
        private int idOcupacionField;
        
        private int idEdoCivilField;
        
        private bool sexoField;
        
        private bool boolEncontradoField;
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre2 {
            get {
                return this.nombre2Field;
            }
            set {
                this.nombre2Field = value;
            }
        }
        
        /// <comentarios/>
        public string ApePat {
            get {
                return this.apePatField;
            }
            set {
                this.apePatField = value;
            }
        }
        
        /// <comentarios/>
        public string ApeMat {
            get {
                return this.apeMatField;
            }
            set {
                this.apeMatField = value;
            }
        }
        
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaIng {
            get {
                return this.fechaIngField;
            }
            set {
                this.fechaIngField = value;
            }
        }
        
        /// <comentarios/>
        public string CURP {
            get {
                return this.cURPField;
            }
            set {
                this.cURPField = value;
            }
        }
        
        /// <comentarios/>
        public int IdCoop {
            get {
                return this.idCoopField;
            }
            set {
                this.idCoopField = value;
            }
        }
        
        /// <comentarios/>
        public int IdPlaza {
            get {
                return this.idPlazaField;
            }
            set {
                this.idPlazaField = value;
            }
        }
        
        /// <comentarios/>
        public int IdSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
        
        /// <comentarios/>
        public int IdOcupacion {
            get {
                return this.idOcupacionField;
            }
            set {
                this.idOcupacionField = value;
            }
        }
        
        /// <comentarios/>
        public int IdEdoCivil {
            get {
                return this.idEdoCivilField;
            }
            set {
                this.idEdoCivilField = value;
            }
        }
        
        /// <comentarios/>
        public bool Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        public bool boolEncontrado {
            get {
                return this.boolEncontradoField;
            }
            set {
                this.boolEncontradoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class IdSocioMA {
        
        private int cIdSocioMA_IdSocField;
        
        /// <comentarios/>
        public int CIdSocioMA_IdSoc {
            get {
                return this.cIdSocioMA_IdSocField;
            }
            set {
                this.cIdSocioMA_IdSocField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class Beneficiario {
        
        private int idField;
        
        private string primerNombreField;
        
        private string segundoNombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string parentescoField;
        
        private string porcentajeField;
        
        private int idParentescoField;
        
        private double porcentaje2Field;
        
        private string estatusField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string PrimerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
            }
        }
        
        /// <comentarios/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
        
        /// <comentarios/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string Parentesco {
            get {
                return this.parentescoField;
            }
            set {
                this.parentescoField = value;
            }
        }
        
        /// <comentarios/>
        public string Porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
            }
        }
        
        /// <comentarios/>
        public int IdParentesco {
            get {
                return this.idParentescoField;
            }
            set {
                this.idParentescoField = value;
            }
        }
        
        /// <comentarios/>
        public double Porcentaje2 {
            get {
                return this.porcentaje2Field;
            }
            set {
                this.porcentaje2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class CURP {
        
        private bool existeField;
        
        private string totalPolizasField;
        
        private string totalCertificadoField;
        
        /// <comentarios/>
        public bool Existe {
            get {
                return this.existeField;
            }
            set {
                this.existeField = value;
            }
        }
        
        /// <comentarios/>
        public string TotalPolizas {
            get {
                return this.totalPolizasField;
            }
            set {
                this.totalPolizasField = value;
            }
        }
        
        /// <comentarios/>
        public string TotalCertificado {
            get {
                return this.totalCertificadoField;
            }
            set {
                this.totalCertificadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class Poliza {
        
        private int idField;
        
        private string numeroField;
        
        private string noSocioField;
        
        private int idCoopField;
        
        private int idAseguradoField;
        
        private string aseguradoField;
        
        private string sumaAseguradaField;
        
        private string primaTotalField;
        
        private string fechaInicioField;
        
        private string fechaFinField;
        
        private string fechaEmisionField;
        
        private bool esDependienteField;
        
        private string socioField;
        
        private string statusField;
        
        private string ladaField;
        
        private string telefonoField;
        
        private string estadoField;
        
        private string municipioField;
        
        private string coloniaField;
        
        private string cpField;
        
        private string calleField;
        
        private string noExtField;
        
        private string noIntField;
        
        private string ocupEspField;
        
        private string fechaNacField;
        
        private int renovacionField;
        
        private string rFCField;
        
        private string linkField;
        
        private string domicilioGralField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <comentarios/>
        public string NoSocio {
            get {
                return this.noSocioField;
            }
            set {
                this.noSocioField = value;
            }
        }
        
        /// <comentarios/>
        public int IdCoop {
            get {
                return this.idCoopField;
            }
            set {
                this.idCoopField = value;
            }
        }
        
        /// <comentarios/>
        public int IdAsegurado {
            get {
                return this.idAseguradoField;
            }
            set {
                this.idAseguradoField = value;
            }
        }
        
        /// <comentarios/>
        public string Asegurado {
            get {
                return this.aseguradoField;
            }
            set {
                this.aseguradoField = value;
            }
        }
        
        /// <comentarios/>
        public string SumaAsegurada {
            get {
                return this.sumaAseguradaField;
            }
            set {
                this.sumaAseguradaField = value;
            }
        }
        
        /// <comentarios/>
        public string PrimaTotal {
            get {
                return this.primaTotalField;
            }
            set {
                this.primaTotalField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
        
        /// <comentarios/>
        public bool EsDependiente {
            get {
                return this.esDependienteField;
            }
            set {
                this.esDependienteField = value;
            }
        }
        
        /// <comentarios/>
        public string Socio {
            get {
                return this.socioField;
            }
            set {
                this.socioField = value;
            }
        }
        
        /// <comentarios/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <comentarios/>
        public string Lada {
            get {
                return this.ladaField;
            }
            set {
                this.ladaField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <comentarios/>
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <comentarios/>
        public string CP {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
            }
        }
        
        /// <comentarios/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <comentarios/>
        public string NoExt {
            get {
                return this.noExtField;
            }
            set {
                this.noExtField = value;
            }
        }
        
        /// <comentarios/>
        public string NoInt {
            get {
                return this.noIntField;
            }
            set {
                this.noIntField = value;
            }
        }
        
        /// <comentarios/>
        public string OcupEsp {
            get {
                return this.ocupEspField;
            }
            set {
                this.ocupEspField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <comentarios/>
        public int Renovacion {
            get {
                return this.renovacionField;
            }
            set {
                this.renovacionField = value;
            }
        }
        
        /// <comentarios/>
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <comentarios/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <comentarios/>
        public string DomicilioGral {
            get {
                return this.domicilioGralField;
            }
            set {
                this.domicilioGralField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class Error {
        
        private string mensajeField;
        
        private bool valorField;
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public bool Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class Parentesco {
        
        private Error errorField;
        
        private int idField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeMS/wsmsp/wsConsultas.asmx")]
    public partial class Sucursal {
        
        private string idField;
        
        private string idPlazaField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string IdPlaza {
            get {
                return this.idPlazaField;
            }
            set {
                this.idPlazaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaDatosPagoCompletedEventHandler(object sender, ConsultaDatosPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDatosPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDatosPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosPago Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosPago)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaIdSucPrybeCompletedEventHandler(object sender, ConsultaIdSucPrybeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaIdSucPrybeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaIdSucPrybeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sucursal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sucursal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaPolizaCompletedEventHandler(object sender, ConsultaPolizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPolizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPolizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaParentescoCompletedEventHandler(object sender, ConsultaParentescoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaParentescoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaParentescoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parentesco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parentesco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaPolizasSocioCompletedEventHandler(object sender, ConsultaPolizasSocioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPolizasSocioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPolizasSocioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Poliza[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Poliza[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CURPExisteCompletedEventHandler(object sender, CURPExisteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CURPExisteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CURPExisteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CURP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CURP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaBeneficiariosCompletedEventHandler(object sender, ConsultaBeneficiariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBeneficiariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBeneficiariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Beneficiario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Beneficiario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ReturnIdSocioMACompletedEventHandler(object sender, ReturnIdSocioMACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnIdSocioMACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnIdSocioMACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IdSocioMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IdSocioMA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ReturnDatMenorAHCompletedEventHandler(object sender, ReturnDatMenorAHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnDatMenorAHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnDatMenorAHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenorAH Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenorAH)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591