//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18213
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18213.
// 
#pragma warning disable 1591

namespace SDA.wsConsultaDatos2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsConsultaSiniestrosSoap", Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class wsConsultaSiniestros : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaSiniestroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPrimaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaReclamosGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaReclamosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDocumentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBeneficiariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBeneficiariosNombresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultasaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaProductosxctaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCuentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCaptacionGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCaptacionDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaColocacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaColocacionDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaReportesBeneficiosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsConsultaSiniestros() {
            this.Url = global::SDA.Properties.Settings.Default.SDA_wsConsultaDatos2_wsConsultaSiniestros;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaSiniestroCompletedEventHandler ConsultaSiniestroCompleted;
        
        /// <remarks/>
        public event ConsultaPrimaCompletedEventHandler ConsultaPrimaCompleted;
        
        /// <remarks/>
        public event ConsultaReclamosGeneralCompletedEventHandler ConsultaReclamosGeneralCompleted;
        
        /// <remarks/>
        public event ConsultaReclamosCompletedEventHandler ConsultaReclamosCompleted;
        
        /// <remarks/>
        public event ConsultaDocumentosCompletedEventHandler ConsultaDocumentosCompleted;
        
        /// <remarks/>
        public event ConsultaBeneficiariosCompletedEventHandler ConsultaBeneficiariosCompleted;
        
        /// <remarks/>
        public event ConsultaBeneficiariosNombresCompletedEventHandler ConsultaBeneficiariosNombresCompleted;
        
        /// <remarks/>
        public event ConsultaProductosCompletedEventHandler ConsultaProductosCompleted;
        
        /// <remarks/>
        public event consultasaldoCompletedEventHandler consultasaldoCompleted;
        
        /// <remarks/>
        public event ConsultaProductosxctaCompletedEventHandler ConsultaProductosxctaCompleted;
        
        /// <remarks/>
        public event ConsultaCuentasCompletedEventHandler ConsultaCuentasCompleted;
        
        /// <remarks/>
        public event ConsultaCaptacionGeneralCompletedEventHandler ConsultaCaptacionGeneralCompleted;
        
        /// <remarks/>
        public event ConsultaCaptacionDetalleCompletedEventHandler ConsultaCaptacionDetalleCompleted;
        
        /// <remarks/>
        public event ConsultaColocacionesCompletedEventHandler ConsultaColocacionesCompleted;
        
        /// <remarks/>
        public event ConsultaColocacionDetalleCompletedEventHandler ConsultaColocacionDetalleCompleted;
        
        /// <remarks/>
        public event ConsultaReportesBeneficiosCompletedEventHandler ConsultaReportesBeneficiosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Siniestro", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaSiniestros[] ConsultaSiniestro() {
            object[] results = this.Invoke("ConsultaSiniestro", new object[0]);
            return ((ConsultaSiniestros[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSiniestroAsync() {
            this.ConsultaSiniestroAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaSiniestroAsync(object userState) {
            if ((this.ConsultaSiniestroOperationCompleted == null)) {
                this.ConsultaSiniestroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSiniestroOperationCompleted);
            }
            this.InvokeAsync("ConsultaSiniestro", new object[0], this.ConsultaSiniestroOperationCompleted, userState);
        }
        
        private void OnConsultaSiniestroOperationCompleted(object arg) {
            if ((this.ConsultaSiniestroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSiniestroCompleted(this, new ConsultaSiniestroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Prima", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaPrimas[] ConsultaPrima() {
            object[] results = this.Invoke("ConsultaPrima", new object[0]);
            return ((ConsultaPrimas[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPrimaAsync() {
            this.ConsultaPrimaAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaPrimaAsync(object userState) {
            if ((this.ConsultaPrimaOperationCompleted == null)) {
                this.ConsultaPrimaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPrimaOperationCompleted);
            }
            this.InvokeAsync("ConsultaPrima", new object[0], this.ConsultaPrimaOperationCompleted, userState);
        }
        
        private void OnConsultaPrimaOperationCompleted(object arg) {
            if ((this.ConsultaPrimaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPrimaCompleted(this, new ConsultaPrimaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "ReclamosGeneral", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaReclamoGeneral[] ConsultaReclamosGeneral(int IdSucursal, int Op, string No_Socio) {
            object[] results = this.Invoke("ConsultaReclamosGeneral", new object[] {
                        IdSucursal,
                        Op,
                        No_Socio});
            return ((ConsultaReclamoGeneral[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaReclamosGeneralAsync(int IdSucursal, int Op, string No_Socio) {
            this.ConsultaReclamosGeneralAsync(IdSucursal, Op, No_Socio, null);
        }
        
        /// <remarks/>
        public void ConsultaReclamosGeneralAsync(int IdSucursal, int Op, string No_Socio, object userState) {
            if ((this.ConsultaReclamosGeneralOperationCompleted == null)) {
                this.ConsultaReclamosGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReclamosGeneralOperationCompleted);
            }
            this.InvokeAsync("ConsultaReclamosGeneral", new object[] {
                        IdSucursal,
                        Op,
                        No_Socio}, this.ConsultaReclamosGeneralOperationCompleted, userState);
        }
        
        private void OnConsultaReclamosGeneralOperationCompleted(object arg) {
            if ((this.ConsultaReclamosGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReclamosGeneralCompleted(this, new ConsultaReclamosGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Reclamos", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaReclamo[] ConsultaReclamos(int IdSucursal, string No_Socio, int Op) {
            object[] results = this.Invoke("ConsultaReclamos", new object[] {
                        IdSucursal,
                        No_Socio,
                        Op});
            return ((ConsultaReclamo[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaReclamosAsync(int IdSucursal, string No_Socio, int Op) {
            this.ConsultaReclamosAsync(IdSucursal, No_Socio, Op, null);
        }
        
        /// <remarks/>
        public void ConsultaReclamosAsync(int IdSucursal, string No_Socio, int Op, object userState) {
            if ((this.ConsultaReclamosOperationCompleted == null)) {
                this.ConsultaReclamosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReclamosOperationCompleted);
            }
            this.InvokeAsync("ConsultaReclamos", new object[] {
                        IdSucursal,
                        No_Socio,
                        Op}, this.ConsultaReclamosOperationCompleted, userState);
        }
        
        private void OnConsultaReclamosOperationCompleted(object arg) {
            if ((this.ConsultaReclamosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReclamosCompleted(this, new ConsultaReclamosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Documentos", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaDocumentoSocio[] ConsultaDocumentos(string numsocio, string idsucursal) {
            object[] results = this.Invoke("ConsultaDocumentos", new object[] {
                        numsocio,
                        idsucursal});
            return ((ConsultaDocumentoSocio[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDocumentosAsync(string numsocio, string idsucursal) {
            this.ConsultaDocumentosAsync(numsocio, idsucursal, null);
        }
        
        /// <remarks/>
        public void ConsultaDocumentosAsync(string numsocio, string idsucursal, object userState) {
            if ((this.ConsultaDocumentosOperationCompleted == null)) {
                this.ConsultaDocumentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDocumentosOperationCompleted);
            }
            this.InvokeAsync("ConsultaDocumentos", new object[] {
                        numsocio,
                        idsucursal}, this.ConsultaDocumentosOperationCompleted, userState);
        }
        
        private void OnConsultaDocumentosOperationCompleted(object arg) {
            if ((this.ConsultaDocumentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDocumentosCompleted(this, new ConsultaDocumentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Beneficiarios", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaBeneficiario[] ConsultaBeneficiarios(string IdReclamo) {
            object[] results = this.Invoke("ConsultaBeneficiarios", new object[] {
                        IdReclamo});
            return ((ConsultaBeneficiario[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBeneficiariosAsync(string IdReclamo) {
            this.ConsultaBeneficiariosAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultaBeneficiariosAsync(string IdReclamo, object userState) {
            if ((this.ConsultaBeneficiariosOperationCompleted == null)) {
                this.ConsultaBeneficiariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBeneficiariosOperationCompleted);
            }
            this.InvokeAsync("ConsultaBeneficiarios", new object[] {
                        IdReclamo}, this.ConsultaBeneficiariosOperationCompleted, userState);
        }
        
        private void OnConsultaBeneficiariosOperationCompleted(object arg) {
            if ((this.ConsultaBeneficiariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBeneficiariosCompleted(this, new ConsultaBeneficiariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "BeneficiariosNombres", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaBeneficiarioNombres ConsultaBeneficiariosNombres(string IdReclamo, int IdBeneficiario) {
            object[] results = this.Invoke("ConsultaBeneficiariosNombres", new object[] {
                        IdReclamo,
                        IdBeneficiario});
            return ((ConsultaBeneficiarioNombres)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBeneficiariosNombresAsync(string IdReclamo, int IdBeneficiario) {
            this.ConsultaBeneficiariosNombresAsync(IdReclamo, IdBeneficiario, null);
        }
        
        /// <remarks/>
        public void ConsultaBeneficiariosNombresAsync(string IdReclamo, int IdBeneficiario, object userState) {
            if ((this.ConsultaBeneficiariosNombresOperationCompleted == null)) {
                this.ConsultaBeneficiariosNombresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBeneficiariosNombresOperationCompleted);
            }
            this.InvokeAsync("ConsultaBeneficiariosNombres", new object[] {
                        IdReclamo,
                        IdBeneficiario}, this.ConsultaBeneficiariosNombresOperationCompleted, userState);
        }
        
        private void OnConsultaBeneficiariosNombresOperationCompleted(object arg) {
            if ((this.ConsultaBeneficiariosNombresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBeneficiariosNombresCompleted(this, new ConsultaBeneficiariosNombresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Productos", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultasProductos[] ConsultaProductos() {
            object[] results = this.Invoke("ConsultaProductos", new object[0]);
            return ((ConsultasProductos[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaProductosAsync() {
            this.ConsultaProductosAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaProductosAsync(object userState) {
            if ((this.ConsultaProductosOperationCompleted == null)) {
                this.ConsultaProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaProductosOperationCompleted);
            }
            this.InvokeAsync("ConsultaProductos", new object[0], this.ConsultaProductosOperationCompleted, userState);
        }
        
        private void OnConsultaProductosOperationCompleted(object arg) {
            if ((this.ConsultaProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaProductosCompleted(this, new ConsultaProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/consulta" +
            "saldo", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaSaldos[] consultasaldo(string nosoc, string idsuc) {
            object[] results = this.Invoke("consultasaldo", new object[] {
                        nosoc,
                        idsuc});
            return ((ConsultaSaldos[])(results[0]));
        }
        
        /// <remarks/>
        public void consultasaldoAsync(string nosoc, string idsuc) {
            this.consultasaldoAsync(nosoc, idsuc, null);
        }
        
        /// <remarks/>
        public void consultasaldoAsync(string nosoc, string idsuc, object userState) {
            if ((this.consultasaldoOperationCompleted == null)) {
                this.consultasaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultasaldoOperationCompleted);
            }
            this.InvokeAsync("consultasaldo", new object[] {
                        nosoc,
                        idsuc}, this.consultasaldoOperationCompleted, userState);
        }
        
        private void OnconsultasaldoOperationCompleted(object arg) {
            if ((this.consultasaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultasaldoCompleted(this, new consultasaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Productosxcta", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaProdxCta[] ConsultaProductosxcta() {
            object[] results = this.Invoke("ConsultaProductosxcta", new object[0]);
            return ((ConsultaProdxCta[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaProductosxctaAsync() {
            this.ConsultaProductosxctaAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaProductosxctaAsync(object userState) {
            if ((this.ConsultaProductosxctaOperationCompleted == null)) {
                this.ConsultaProductosxctaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaProductosxctaOperationCompleted);
            }
            this.InvokeAsync("ConsultaProductosxcta", new object[0], this.ConsultaProductosxctaOperationCompleted, userState);
        }
        
        private void OnConsultaProductosxctaOperationCompleted(object arg) {
            if ((this.ConsultaProductosxctaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaProductosxctaCompleted(this, new ConsultaProductosxctaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Cuentas", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuentas[] ConsultaCuentas(string IdCoop, int Id_Tipo_Cta) {
            object[] results = this.Invoke("ConsultaCuentas", new object[] {
                        IdCoop,
                        Id_Tipo_Cta});
            return ((Cuentas[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCuentasAsync(string IdCoop, int Id_Tipo_Cta) {
            this.ConsultaCuentasAsync(IdCoop, Id_Tipo_Cta, null);
        }
        
        /// <remarks/>
        public void ConsultaCuentasAsync(string IdCoop, int Id_Tipo_Cta, object userState) {
            if ((this.ConsultaCuentasOperationCompleted == null)) {
                this.ConsultaCuentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCuentasOperationCompleted);
            }
            this.InvokeAsync("ConsultaCuentas", new object[] {
                        IdCoop,
                        Id_Tipo_Cta}, this.ConsultaCuentasOperationCompleted, userState);
        }
        
        private void OnConsultaCuentasOperationCompleted(object arg) {
            if ((this.ConsultaCuentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCuentasCompleted(this, new ConsultaCuentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "CaptacionGeneral", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaCaptacion[] ConsultaCaptacionGeneral(string IdReclamo) {
            object[] results = this.Invoke("ConsultaCaptacionGeneral", new object[] {
                        IdReclamo});
            return ((ConsultaCaptacion[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCaptacionGeneralAsync(string IdReclamo) {
            this.ConsultaCaptacionGeneralAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultaCaptacionGeneralAsync(string IdReclamo, object userState) {
            if ((this.ConsultaCaptacionGeneralOperationCompleted == null)) {
                this.ConsultaCaptacionGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCaptacionGeneralOperationCompleted);
            }
            this.InvokeAsync("ConsultaCaptacionGeneral", new object[] {
                        IdReclamo}, this.ConsultaCaptacionGeneralOperationCompleted, userState);
        }
        
        private void OnConsultaCaptacionGeneralOperationCompleted(object arg) {
            if ((this.ConsultaCaptacionGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCaptacionGeneralCompleted(this, new ConsultaCaptacionGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "CaptacionDetalle", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaCaptaciones ConsultaCaptacionDetalle(string IdReclamo, string IdCaptacion) {
            object[] results = this.Invoke("ConsultaCaptacionDetalle", new object[] {
                        IdReclamo,
                        IdCaptacion});
            return ((ConsultaCaptaciones)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCaptacionDetalleAsync(string IdReclamo, string IdCaptacion) {
            this.ConsultaCaptacionDetalleAsync(IdReclamo, IdCaptacion, null);
        }
        
        /// <remarks/>
        public void ConsultaCaptacionDetalleAsync(string IdReclamo, string IdCaptacion, object userState) {
            if ((this.ConsultaCaptacionDetalleOperationCompleted == null)) {
                this.ConsultaCaptacionDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCaptacionDetalleOperationCompleted);
            }
            this.InvokeAsync("ConsultaCaptacionDetalle", new object[] {
                        IdReclamo,
                        IdCaptacion}, this.ConsultaCaptacionDetalleOperationCompleted, userState);
        }
        
        private void OnConsultaCaptacionDetalleOperationCompleted(object arg) {
            if ((this.ConsultaCaptacionDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCaptacionDetalleCompleted(this, new ConsultaCaptacionDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "Colocaciones", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaColocacion[] ConsultaColocaciones(string IdReclamo) {
            object[] results = this.Invoke("ConsultaColocaciones", new object[] {
                        IdReclamo});
            return ((ConsultaColocacion[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaColocacionesAsync(string IdReclamo) {
            this.ConsultaColocacionesAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultaColocacionesAsync(string IdReclamo, object userState) {
            if ((this.ConsultaColocacionesOperationCompleted == null)) {
                this.ConsultaColocacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaColocacionesOperationCompleted);
            }
            this.InvokeAsync("ConsultaColocaciones", new object[] {
                        IdReclamo}, this.ConsultaColocacionesOperationCompleted, userState);
        }
        
        private void OnConsultaColocacionesOperationCompleted(object arg) {
            if ((this.ConsultaColocacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaColocacionesCompleted(this, new ConsultaColocacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "ColocacionDetalle", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultasColocaciones ConsultaColocacionDetalle(string IdReclamo, string IdColocacion) {
            object[] results = this.Invoke("ConsultaColocacionDetalle", new object[] {
                        IdReclamo,
                        IdColocacion});
            return ((ConsultasColocaciones)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaColocacionDetalleAsync(string IdReclamo, string IdColocacion) {
            this.ConsultaColocacionDetalleAsync(IdReclamo, IdColocacion, null);
        }
        
        /// <remarks/>
        public void ConsultaColocacionDetalleAsync(string IdReclamo, string IdColocacion, object userState) {
            if ((this.ConsultaColocacionDetalleOperationCompleted == null)) {
                this.ConsultaColocacionDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaColocacionDetalleOperationCompleted);
            }
            this.InvokeAsync("ConsultaColocacionDetalle", new object[] {
                        IdReclamo,
                        IdColocacion}, this.ConsultaColocacionDetalleOperationCompleted, userState);
        }
        
        private void OnConsultaColocacionDetalleOperationCompleted(object arg) {
            if ((this.ConsultaColocacionDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaColocacionDetalleCompleted(this, new ConsultaColocacionDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx/Consulta" +
            "ReportesBeneficios", RequestNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", ResponseNamespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaReportes[] ConsultaReportesBeneficios(string IdReclamo) {
            object[] results = this.Invoke("ConsultaReportesBeneficios", new object[] {
                        IdReclamo});
            return ((ConsultaReportes[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaReportesBeneficiosAsync(string IdReclamo) {
            this.ConsultaReportesBeneficiosAsync(IdReclamo, null);
        }
        
        /// <remarks/>
        public void ConsultaReportesBeneficiosAsync(string IdReclamo, object userState) {
            if ((this.ConsultaReportesBeneficiosOperationCompleted == null)) {
                this.ConsultaReportesBeneficiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReportesBeneficiosOperationCompleted);
            }
            this.InvokeAsync("ConsultaReportesBeneficios", new object[] {
                        IdReclamo}, this.ConsultaReportesBeneficiosOperationCompleted, userState);
        }
        
        private void OnConsultaReportesBeneficiosOperationCompleted(object arg) {
            if ((this.ConsultaReportesBeneficiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReportesBeneficiosCompleted(this, new ConsultaReportesBeneficiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaSiniestros {
        
        private string coopField;
        
        private string numField;
        
        private string prestamoField;
        
        private string ahorroField;
        
        private string funerarioField;
        
        private string mutualField;
        
        private string prodosField;
        
        private string montomesField;
        
        private string reclamosacumField;
        
        private string montoacumField;
        
        /// <comentarios/>
        public string Coop {
            get {
                return this.coopField;
            }
            set {
                this.coopField = value;
            }
        }
        
        /// <comentarios/>
        public string Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <comentarios/>
        public string Prestamo {
            get {
                return this.prestamoField;
            }
            set {
                this.prestamoField = value;
            }
        }
        
        /// <comentarios/>
        public string Ahorro {
            get {
                return this.ahorroField;
            }
            set {
                this.ahorroField = value;
            }
        }
        
        /// <comentarios/>
        public string Funerario {
            get {
                return this.funerarioField;
            }
            set {
                this.funerarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Mutual {
            get {
                return this.mutualField;
            }
            set {
                this.mutualField = value;
            }
        }
        
        /// <comentarios/>
        public string Prodos {
            get {
                return this.prodosField;
            }
            set {
                this.prodosField = value;
            }
        }
        
        /// <comentarios/>
        public string Montomes {
            get {
                return this.montomesField;
            }
            set {
                this.montomesField = value;
            }
        }
        
        /// <comentarios/>
        public string Reclamosacum {
            get {
                return this.reclamosacumField;
            }
            set {
                this.reclamosacumField = value;
            }
        }
        
        /// <comentarios/>
        public string Montoacum {
            get {
                return this.montoacumField;
            }
            set {
                this.montoacumField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaReportes {
        
        private string nombreBeneficiarioField;
        
        private string nombreField;
        
        private string noSocioField;
        
        private string idCoopField;
        
        private string coopField;
        
        private string apoyoFunerarioField;
        
        private string numeroPolizaField;
        
        private string plazaField;
        
        private string sucursalField;
        
        private string numeroReclamoField;
        
        private string idBeneficiarioField;
        
        /// <comentarios/>
        public string NombreBeneficiario {
            get {
                return this.nombreBeneficiarioField;
            }
            set {
                this.nombreBeneficiarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NoSocio {
            get {
                return this.noSocioField;
            }
            set {
                this.noSocioField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCoop {
            get {
                return this.idCoopField;
            }
            set {
                this.idCoopField = value;
            }
        }
        
        /// <comentarios/>
        public string Coop {
            get {
                return this.coopField;
            }
            set {
                this.coopField = value;
            }
        }
        
        /// <comentarios/>
        public string ApoyoFunerario {
            get {
                return this.apoyoFunerarioField;
            }
            set {
                this.apoyoFunerarioField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroPoliza {
            get {
                return this.numeroPolizaField;
            }
            set {
                this.numeroPolizaField = value;
            }
        }
        
        /// <comentarios/>
        public string Plaza {
            get {
                return this.plazaField;
            }
            set {
                this.plazaField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string NumeroReclamo {
            get {
                return this.numeroReclamoField;
            }
            set {
                this.numeroReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdBeneficiario {
            get {
                return this.idBeneficiarioField;
            }
            set {
                this.idBeneficiarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultasColocaciones {
        
        private string montoField;
        
        private string fechaPrestField;
        
        private string ultimoMovColocacionField;
        
        private string idColocacionField;
        
        private string idTipoPrestamoField;
        
        private string tasaIntField;
        
        private string plazoField;
        
        private string saldoColocacionField;
        
        /// <comentarios/>
        public string Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaPrest {
            get {
                return this.fechaPrestField;
            }
            set {
                this.fechaPrestField = value;
            }
        }
        
        /// <comentarios/>
        public string UltimoMovColocacion {
            get {
                return this.ultimoMovColocacionField;
            }
            set {
                this.ultimoMovColocacionField = value;
            }
        }
        
        /// <comentarios/>
        public string IdColocacion {
            get {
                return this.idColocacionField;
            }
            set {
                this.idColocacionField = value;
            }
        }
        
        /// <comentarios/>
        public string IdTipoPrestamo {
            get {
                return this.idTipoPrestamoField;
            }
            set {
                this.idTipoPrestamoField = value;
            }
        }
        
        /// <comentarios/>
        public string TasaInt {
            get {
                return this.tasaIntField;
            }
            set {
                this.tasaIntField = value;
            }
        }
        
        /// <comentarios/>
        public string Plazo {
            get {
                return this.plazoField;
            }
            set {
                this.plazoField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoColocacion {
            get {
                return this.saldoColocacionField;
            }
            set {
                this.saldoColocacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaColocacion {
        
        private System.DateTime fechaPrestamoField;
        
        private System.DateTime ultimoMovimientoColocacionField;
        
        private string plazoField;
        
        private string tasaIntField;
        
        private string idAnalisisField;
        
        private string montoField;
        
        private string saldoTotalField;
        
        private string idColocacionField;
        
        private string tipoPrestamoField;
        
        private string saldoColocacionField;
        
        private string interesesCubrirField;
        
        /// <comentarios/>
        public System.DateTime FechaPrestamo {
            get {
                return this.fechaPrestamoField;
            }
            set {
                this.fechaPrestamoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime UltimoMovimientoColocacion {
            get {
                return this.ultimoMovimientoColocacionField;
            }
            set {
                this.ultimoMovimientoColocacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Plazo {
            get {
                return this.plazoField;
            }
            set {
                this.plazoField = value;
            }
        }
        
        /// <comentarios/>
        public string TasaInt {
            get {
                return this.tasaIntField;
            }
            set {
                this.tasaIntField = value;
            }
        }
        
        /// <comentarios/>
        public string IdAnalisis {
            get {
                return this.idAnalisisField;
            }
            set {
                this.idAnalisisField = value;
            }
        }
        
        /// <comentarios/>
        public string Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoTotal {
            get {
                return this.saldoTotalField;
            }
            set {
                this.saldoTotalField = value;
            }
        }
        
        /// <comentarios/>
        public string IdColocacion {
            get {
                return this.idColocacionField;
            }
            set {
                this.idColocacionField = value;
            }
        }
        
        /// <comentarios/>
        public string TipoPrestamo {
            get {
                return this.tipoPrestamoField;
            }
            set {
                this.tipoPrestamoField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoColocacion {
            get {
                return this.saldoColocacionField;
            }
            set {
                this.saldoColocacionField = value;
            }
        }
        
        /// <comentarios/>
        public string InteresesCubrir {
            get {
                return this.interesesCubrirField;
            }
            set {
                this.interesesCubrirField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaCaptaciones {
        
        private string saldoField;
        
        private string ultimoMovimientoField;
        
        private string idAnalisisField;
        
        private string idCaptacionField;
        
        private string captacionField;
        
        private bool aditamentoJField;
        
        private bool dobleIField;
        
        /// <comentarios/>
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <comentarios/>
        public string UltimoMovimiento {
            get {
                return this.ultimoMovimientoField;
            }
            set {
                this.ultimoMovimientoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdAnalisis {
            get {
                return this.idAnalisisField;
            }
            set {
                this.idAnalisisField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCaptacion {
            get {
                return this.idCaptacionField;
            }
            set {
                this.idCaptacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Captacion {
            get {
                return this.captacionField;
            }
            set {
                this.captacionField = value;
            }
        }
        
        /// <comentarios/>
        public bool AditamentoJ {
            get {
                return this.aditamentoJField;
            }
            set {
                this.aditamentoJField = value;
            }
        }
        
        /// <comentarios/>
        public bool DobleI {
            get {
                return this.dobleIField;
            }
            set {
                this.dobleIField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaCaptacion {
        
        private string saldoField;
        
        private System.DateTime ultimoMovimientoField;
        
        private string idAnalisisField;
        
        private string idCaptacionField;
        
        private string cuentaField;
        
        private bool aditamentoJField;
        
        private bool dobleIField;
        
        private string porcetajeAditamentoField;
        
        private string saldoTotalField;
        
        /// <comentarios/>
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime UltimoMovimiento {
            get {
                return this.ultimoMovimientoField;
            }
            set {
                this.ultimoMovimientoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdAnalisis {
            get {
                return this.idAnalisisField;
            }
            set {
                this.idAnalisisField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCaptacion {
            get {
                return this.idCaptacionField;
            }
            set {
                this.idCaptacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public bool AditamentoJ {
            get {
                return this.aditamentoJField;
            }
            set {
                this.aditamentoJField = value;
            }
        }
        
        /// <comentarios/>
        public bool DobleI {
            get {
                return this.dobleIField;
            }
            set {
                this.dobleIField = value;
            }
        }
        
        /// <comentarios/>
        public string PorcetajeAditamento {
            get {
                return this.porcetajeAditamentoField;
            }
            set {
                this.porcetajeAditamentoField = value;
            }
        }
        
        /// <comentarios/>
        public string SaldoTotal {
            get {
                return this.saldoTotalField;
            }
            set {
                this.saldoTotalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class Cuentas {
        
        private string cuentaField;
        
        private string idCoopField;
        
        private string idCuentaField;
        
        /// <comentarios/>
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCoop {
            get {
                return this.idCoopField;
            }
            set {
                this.idCoopField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCuenta {
            get {
                return this.idCuentaField;
            }
            set {
                this.idCuentaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaProdxCta {
        
        private string id_ProdxctaField;
        
        private string id_ProdField;
        
        private string id_CuentaField;
        
        /// <comentarios/>
        public string Id_Prodxcta {
            get {
                return this.id_ProdxctaField;
            }
            set {
                this.id_ProdxctaField = value;
            }
        }
        
        /// <comentarios/>
        public string Id_Prod {
            get {
                return this.id_ProdField;
            }
            set {
                this.id_ProdField = value;
            }
        }
        
        /// <comentarios/>
        public string Id_Cuenta {
            get {
                return this.id_CuentaField;
            }
            set {
                this.id_CuentaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaSaldos {
        
        private string totalField;
        
        /// <comentarios/>
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultasProductos {
        
        private string id_ProdField;
        
        private string productoField;
        
        /// <comentarios/>
        public string Id_Prod {
            get {
                return this.id_ProdField;
            }
            set {
                this.id_ProdField = value;
            }
        }
        
        /// <comentarios/>
        public string Producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaBeneficiarioNombres {
        
        private string nombre1Field;
        
        private string nombre2Field;
        
        private string apellidoPatField;
        
        private string apellidoMatField;
        
        private string porcentajeField;
        
        private string idBeneficiarioField;
        
        /// <comentarios/>
        public string Nombre1 {
            get {
                return this.nombre1Field;
            }
            set {
                this.nombre1Field = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre2 {
            get {
                return this.nombre2Field;
            }
            set {
                this.nombre2Field = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidoPat {
            get {
                return this.apellidoPatField;
            }
            set {
                this.apellidoPatField = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidoMat {
            get {
                return this.apellidoMatField;
            }
            set {
                this.apellidoMatField = value;
            }
        }
        
        /// <comentarios/>
        public string Porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
            }
        }
        
        /// <comentarios/>
        public string IdBeneficiario {
            get {
                return this.idBeneficiarioField;
            }
            set {
                this.idBeneficiarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaBeneficiario {
        
        private string nombreBeneficiarioField;
        
        private string porcentajeField;
        
        private string idBeneficiarioField;
        
        /// <comentarios/>
        public string NombreBeneficiario {
            get {
                return this.nombreBeneficiarioField;
            }
            set {
                this.nombreBeneficiarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
            }
        }
        
        /// <comentarios/>
        public string IdBeneficiario {
            get {
                return this.idBeneficiarioField;
            }
            set {
                this.idBeneficiarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaDocumentoSocio {
        
        private string documentoField;
        
        private string idDocumentoField;
        
        /// <comentarios/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                this.idDocumentoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaReclamo {
        
        private string numSocioField;
        
        private string nombreField;
        
        private string numReclamoField;
        
        private System.DateTime fechaRecField;
        
        private string sucursalField;
        
        private string ocupacionField;
        
        private string anoReclamoField;
        
        private string estadoBField;
        
        private string idReclamoField;
        
        private string idSucursalField;
        
        /// <comentarios/>
        public string NumSocio {
            get {
                return this.numSocioField;
            }
            set {
                this.numSocioField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NumReclamo {
            get {
                return this.numReclamoField;
            }
            set {
                this.numReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaRec {
            get {
                return this.fechaRecField;
            }
            set {
                this.fechaRecField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
            }
        }
        
        /// <comentarios/>
        public string AnoReclamo {
            get {
                return this.anoReclamoField;
            }
            set {
                this.anoReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string EstadoB {
            get {
                return this.estadoBField;
            }
            set {
                this.estadoBField = value;
            }
        }
        
        /// <comentarios/>
        public string IdReclamo {
            get {
                return this.idReclamoField;
            }
            set {
                this.idReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaReclamoGeneral {
        
        private string numSocioField;
        
        private string nombreField;
        
        private string numReclamoField;
        
        private System.DateTime fechaRecField;
        
        private string sucursalField;
        
        private string ocupacionField;
        
        private string anoReclamoField;
        
        private string estadoBField;
        
        private string idReclamoField;
        
        private string idSucursalField;
        
        /// <comentarios/>
        public string NumSocio {
            get {
                return this.numSocioField;
            }
            set {
                this.numSocioField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NumReclamo {
            get {
                return this.numReclamoField;
            }
            set {
                this.numReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaRec {
            get {
                return this.fechaRecField;
            }
            set {
                this.fechaRecField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
            }
        }
        
        /// <comentarios/>
        public string AnoReclamo {
            get {
                return this.anoReclamoField;
            }
            set {
                this.anoReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string EstadoB {
            get {
                return this.estadoBField;
            }
            set {
                this.estadoBField = value;
            }
        }
        
        /// <comentarios/>
        public string IdReclamo {
            get {
                return this.idReclamoField;
            }
            set {
                this.idReclamoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qa.prybe.coop/WSPrybeBeneficios/wspbene/wsConsultaSiniestros.asmx")]
    public partial class ConsultaPrimas {
        
        private string plazaField;
        
        private string prestamosField;
        
        private string ahMayoresField;
        
        private string ahMenoresField;
        
        private string ppField;
        
        private string pAmenoresField;
        
        private string basicaField;
        
        private string dobleIField;
        
        private string aditamentoJField;
        
        private string edad1Field;
        
        private string edad2Field;
        
        private string edad3Field;
        
        private string coberturaField;
        
        private string funerario1Field;
        
        private string funerario2Field;
        
        private string funerario3Field;
        
        private string funerarioFunField;
        
        private string totalPField;
        
        /// <comentarios/>
        public string Plaza {
            get {
                return this.plazaField;
            }
            set {
                this.plazaField = value;
            }
        }
        
        /// <comentarios/>
        public string Prestamos {
            get {
                return this.prestamosField;
            }
            set {
                this.prestamosField = value;
            }
        }
        
        /// <comentarios/>
        public string AhMayores {
            get {
                return this.ahMayoresField;
            }
            set {
                this.ahMayoresField = value;
            }
        }
        
        /// <comentarios/>
        public string AhMenores {
            get {
                return this.ahMenoresField;
            }
            set {
                this.ahMenoresField = value;
            }
        }
        
        /// <comentarios/>
        public string PP {
            get {
                return this.ppField;
            }
            set {
                this.ppField = value;
            }
        }
        
        /// <comentarios/>
        public string PAmenores {
            get {
                return this.pAmenoresField;
            }
            set {
                this.pAmenoresField = value;
            }
        }
        
        /// <comentarios/>
        public string Basica {
            get {
                return this.basicaField;
            }
            set {
                this.basicaField = value;
            }
        }
        
        /// <comentarios/>
        public string DobleI {
            get {
                return this.dobleIField;
            }
            set {
                this.dobleIField = value;
            }
        }
        
        /// <comentarios/>
        public string AditamentoJ {
            get {
                return this.aditamentoJField;
            }
            set {
                this.aditamentoJField = value;
            }
        }
        
        /// <comentarios/>
        public string Edad1 {
            get {
                return this.edad1Field;
            }
            set {
                this.edad1Field = value;
            }
        }
        
        /// <comentarios/>
        public string Edad2 {
            get {
                return this.edad2Field;
            }
            set {
                this.edad2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Edad3 {
            get {
                return this.edad3Field;
            }
            set {
                this.edad3Field = value;
            }
        }
        
        /// <comentarios/>
        public string Cobertura {
            get {
                return this.coberturaField;
            }
            set {
                this.coberturaField = value;
            }
        }
        
        /// <comentarios/>
        public string Funerario1 {
            get {
                return this.funerario1Field;
            }
            set {
                this.funerario1Field = value;
            }
        }
        
        /// <comentarios/>
        public string Funerario2 {
            get {
                return this.funerario2Field;
            }
            set {
                this.funerario2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Funerario3 {
            get {
                return this.funerario3Field;
            }
            set {
                this.funerario3Field = value;
            }
        }
        
        /// <comentarios/>
        public string FunerarioFun {
            get {
                return this.funerarioFunField;
            }
            set {
                this.funerarioFunField = value;
            }
        }
        
        /// <comentarios/>
        public string TotalP {
            get {
                return this.totalPField;
            }
            set {
                this.totalPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaSiniestroCompletedEventHandler(object sender, ConsultaSiniestroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSiniestroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSiniestroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaSiniestros[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaSiniestros[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaPrimaCompletedEventHandler(object sender, ConsultaPrimaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPrimaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPrimaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaPrimas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaPrimas[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaReclamosGeneralCompletedEventHandler(object sender, ConsultaReclamosGeneralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReclamosGeneralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaReclamosGeneralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaReclamoGeneral[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaReclamoGeneral[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaReclamosCompletedEventHandler(object sender, ConsultaReclamosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReclamosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaReclamosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaReclamo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaReclamo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaDocumentosCompletedEventHandler(object sender, ConsultaDocumentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDocumentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDocumentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaDocumentoSocio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaDocumentoSocio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaBeneficiariosCompletedEventHandler(object sender, ConsultaBeneficiariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBeneficiariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBeneficiariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaBeneficiario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaBeneficiario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaBeneficiariosNombresCompletedEventHandler(object sender, ConsultaBeneficiariosNombresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBeneficiariosNombresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBeneficiariosNombresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaBeneficiarioNombres Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaBeneficiarioNombres)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaProductosCompletedEventHandler(object sender, ConsultaProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultasProductos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultasProductos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void consultasaldoCompletedEventHandler(object sender, consultasaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultasaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultasaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaSaldos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaSaldos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaProductosxctaCompletedEventHandler(object sender, ConsultaProductosxctaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaProductosxctaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaProductosxctaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaProdxCta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaProdxCta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaCuentasCompletedEventHandler(object sender, ConsultaCuentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCuentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCuentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuentas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuentas[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaCaptacionGeneralCompletedEventHandler(object sender, ConsultaCaptacionGeneralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCaptacionGeneralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCaptacionGeneralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaCaptacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaCaptacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaCaptacionDetalleCompletedEventHandler(object sender, ConsultaCaptacionDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCaptacionDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCaptacionDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaCaptaciones Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaCaptaciones)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaColocacionesCompletedEventHandler(object sender, ConsultaColocacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaColocacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaColocacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaColocacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaColocacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaColocacionDetalleCompletedEventHandler(object sender, ConsultaColocacionDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaColocacionDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaColocacionDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultasColocaciones Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultasColocaciones)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaReportesBeneficiosCompletedEventHandler(object sender, ConsultaReportesBeneficiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReportesBeneficiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaReportesBeneficiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaReportes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaReportes[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591